### ISSUE TITLE
Find a web designer/UX person for community site

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#10]
To ensure we start with a good quality site and make this a community effort, we should put out a call for community voluneers with web/ux experience to provide input to the new site (or even design it) based on our list of requirements.

**Comment by cybette** [comment]
Meetings lined up with several design / UX experts in RH to discuss with and consult them

**Comment by samccann** [comment]
Some feedback from one of those meetings:

https://containers.github.io/website-new/community
- using tailwind
 - inserts md based content into react components
 - typescript?
 - will have blog integrated (wordpress via OSPO) and thus no extra cost
 - will integrate the docs with docusaurus

- base the stack on what the team is familiar with
- it's static

https://stg.fedoraproject.org/
 -using viewjs
 - lightweight CMS driving it. The contributors are not technical

ansible coloring book has some cute artwork and cute bull https://github.com/FOSS-Coloring-Books/ansible
These are brand-approved graphics in the coloring book

**Comment by cybette** [comment]
Several members from the Ansible UI/UX team are joining in the effort, including a CSS expert! Thanks to @Spredzy for making the connections.

**Comment by oraNod** [comment]
Closing this as we have the Ansible UI/UX team joining the effort. Thanks @Spredzy
