### ISSUE TITLE
Review and finalize wording on the "Why Ansible" band

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#101]
Follow up on https://github.com/ansible-community/community-website/pull/92 to ensure the content in the "Why Ansible" band is as good as it should be.

**Comment by oraNod** [comment]
@tiyiprh Would it be possible for you to review the wording on the "Why Ansible" band with your colleague who has provided feedback on some of the other sections?

We can review this with others too but I think some of the original text was inherited from the marketing content on redhat.com and was perhaps too "enterprise-focused" for community. Any suggestions or additional input we could get here would be great. Thanks!

**Comment by oraNod** [comment]
@tiyiprh Thanks for the suggestions. I feel like those changes are a little too drastic in the amount that they reduce. Let's keep the text as-is for now and I'll start a post in the new forum tomorrow to ask the community for their feedback. It'd be good to get their input on it as well and maybe gauge the reaction to the current text.

FWIW it would be better not to link to google docs in public repositories. Those docs are restricted to Red Hat employees so aren't accessible to the community. A decent alternative is https://hackmd.io/

**Comment by willthames** [comment]
I think it's more important from a new user perspective to answer 'What is ansible' first, and then 'Why ansible' 

If I didn't know what ansible was, I'm not sure the current text helps me very much

**Comment by oraNod** [comment]
@willthames Thanks for that. I agree and have taken a stab at it in the linked PR. I'd appreciate getting your thoughts on the updated text.

**Comment by willthames** [comment]
@oraNod the PR reads well - is there a link to the preview version that I could look at the rendered result?

**Comment by oraNod** [comment]
@willthames Thank you. Yes, you can find the preview version here: https://ansible-community-website--251.org.readthedocs.build/en/251/

**Comment by willthames** [comment]
@oraNod I'm happy with that change, LGTM

**Comment by oraNod** [comment]
Thanks for the review and insights @willthames and @tiyiprh
