### ISSUE TITLE
Wireframe: Code of Conduct link

### ISSUE THREAD

**Issue by GregSutcliffe** [ansible-community/community-website#107]
Moved from #80 / #104 - the CoC section should probably be a band of it's own at the very least.

I note that the CoC isn't in the wireframes, although I do agree it needs a place. I wonder if a footer link rather than a band is the way to go? We already have the privacy policy down there....

**Comment by oraNod** [comment]
Here are the relevant portions from the related PR: https://gist.github.com/oraNod/5b30f8fe15817d1aa5ddc69df92a2ee6

**Comment by oraNod** [comment]
Maybe we can do something like Fedora and put this just above the footer with some other info:

![image](https://github.com/ansible-community/community-website/assets/32749632/0d914c3d-765a-4c65-88da-5e04782a6d9a)

**Comment by oraNod** [comment]
@GregSutcliffe I think a footer link is the way to go, at least for now. It's important to make the CoC available on the website but I'm not sure we need to make it prominent in a band of its own or anything.
