### ISSUE TITLE
Identify Ansible community personas and develop user journeys

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#11]
We have an existing effort to [define docsite personas](https://github.com/ansible-community/community-topics/issues/175). We should ensure that also covers the new community site, or finalize any additions/changes to that for the community website as a whole.

**Comment by oraNod** [comment]
I'm going to go ahead and close this one. https://github.com/ansible-community/community-website/commit/a9b2974984f6151905fc8e5433c1ea423cab7bf0 sets up the personas and journeys. This isn't probably something we will ever stop doing, at least hopefully. We might identify a core set of personas but I expect personas will come and go naturally over time. And the user journeys will continue to evolve as well, for the most part.
