### ISSUE TITLE
Create content on  the community frontpage 

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#12]
Based on the defined user journeys, create the front page content of the new community site, with community input.

**Comment by samccann** [comment]
There is an immediate ask for someone to do the following as a step toward this front page:

1. create a PR off @oraNod 's prototype branch.
2. Replace the latin at [this line](https://github.com/oraNod/community-website/blob/332d31908c3b2d00f344b7ec052ce4b0a64d354a/themes/ansible-community/templates/homepage-ansible-band.tmpl#L3)  with the temporary Ansible community mission statement: "Automation powered by people"
3. Add another sentence, something like "Open-source and collaboration are at the heart of the Ansible community, helping more people experience the power of automation and work better and faster together."

Needs to be done in the next three hours or so. If you are taking this on, please add a comment here so the rest of us know. Conversations/questions happening in https://matrix.to/#/#website:ansible.com if you need help.
  
5.

**Comment by maxamillion** [comment]
@samccann I'm on it

**Comment by oraNod** [comment]
Thanks @samccann and @maxamillion I think we can close this as done.
