### ISSUE TITLE
Evaluate existing community pages for addition to community site

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#13]
We have community details in a number of places. We should review and determine what should go on the community site:

- [ ]  https://docs.ansible.com/ansible/latest/community/index.html
- [ ] Existing Ansible.com community details
- [ ] stuff for matrix and github and wiki pages etc

**Comment by oraNod** [comment]
I think this one is fairly well covered by a number of other issues and PRs, plus that HackMD. I'll go ahead and close this. Thanks @samccann
