### ISSUE TITLE
Internal linking for homepage navigation

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#14]
We need an image or two that clearly maps out the main projects in the Ansible ecosystem. Ideally, this image has clickable links to each of the projects so readers can hop directly there. Something like the [Saltstack getting started](https://docs.saltproject.io/en/getstarted/index.html) image.

**Comment by oraNod** [comment]
@leogallego has suggested that we create clickable sections within the homepage for the ecosystem and getting started. Here's a screengrab:

![image](https://user-images.githubusercontent.com/32749632/232470543-5df222b8-400d-429d-8de5-848a9f0f217c.png)


I think we could use js to do this quite similarly to how the toggle works on the docsite. We can add data fields to the target sections and call `onClick()` from the images.
