### ISSUE TITLE
User journey based content for pages

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#15]
Identify, define, and design any other subpages on the website.

Note the main page and the docs landing page are covered in other issues.

**Comment by oraNod** [comment]
@samccann This feels sort of like an umbrella task but I think what would be useful to complete this issue might be establishing the pattern of HOW we build pages. A rough sketch of how we go about this is like so:

- Identify the relevant personas and their needs
- Map out the corresponding journeys
- Provide content in MD under the `pages` directory of the site

To be clear I am taking about content design - so I'll update the title of this issue so there's no ambiguity with ux design. For pages that should come with whatever nikola theme we use.

**Comment by oraNod** [comment]
I think we can mark this one as completed as I think we're all on-board with the journey-based approach.
