### ISSUE TITLE
Preview builds

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#16]
We will need a way to test changes to the community site without impacting the existing published site (when it exists :-).

T

**Comment by samccann** [comment]
@oraNod @GregSutcliffe - from the sounds of the website WG discussion, should this issue be changed to 'publish to github pages for test on each PR" or something?

**Comment by oraNod** [comment]
@samccann That sounds about right. We could probably use this action: https://github.com/marketplace/actions/deploy-pr-preview

That actually looks kinda promising and is more or less what I was thinking, some kind of `pr-preview` directory. I'm not sure how well that action plays with the nikola deploy action though.

**Comment by oraNod** [comment]
@samccann Yeah someone from the community could. I wonder if we should hold off for timing though.
