### ISSUE TITLE
Hero/banner section design updates

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#179]
**HERO/BANNER section updates:**

- The blog dropdown on the masthead should mimic the [PF component](https://www.patternfly.org/components/menus/dropdown#examples) and mimic the interaction on the navigation below this section. The background would be the same grey: black-200 #F0F0F0 and turn white on hover
<img width="294" alt="header issue2" src="https://github.com/ansible-community/community-website/assets/98424339/06f65ee6-ff06-4ada-afcb-ad81122d6f59">

- The content within the card area should have 32 px of padding around all sides
- The title should be updated to "Automation powered by people" (sentence case) and should be RH Display with a font size of 36 px / bold and 16 px of padding to the subtext
- The subtext should have a font size of 20 px / medium and 24 px of padding to the buttons. The subtext needs to be updated to: "Configure operating systems, deploy software, orchestrate advanced workflows to support application deployment and system updates, and more!"
- The "pip install" button should have the icon to the right - updated on [PR-168](https://github.com/ansible-community/community-website/pull/168)
- The padding from the buttons to the "Learn more about RH AAP" is 24 px.
- The "Learn more" should use RH Text and have a font size of 18 px/ medium and have a right arrow attached to the end
- The RH icon in the "Learn more" should not have any left padding and be aligned to the rest of the content
- Updated bullito image and adjust height as described in [PR-167](https://github.com/ansible-community/community-website/pull/167)
- Some other updates found in [PR-168](https://github.com/ansible-community/community-website/pull/168)

Mockup:
<img width="515" alt="Screenshot 2023-09-26 at 10 03 00 AM" src="https://github.com/ansible-community/community-website/assets/98424339/76084777-efe8-4483-86e6-e0e789484138">

Updated Marvel: https://marvelapp.com/prototype/8bgeig6

**Comment by oraNod** [comment]
@tiyiprh I wonder about the changes to the banner subtext.

**Current:** Configure most operating systems, deploy software, and orchestrate advanced workflows to support application deployment, system updates, and more!

**Suggested:** Configure operating systems, deploy software, orchestrate advanced workflows to support application deployment and system updates, and more!

The suggestion changes meaning. In the current version we're saying Ansible can orchestrate advanced workflows for 

- application deployment
- system updates
- and more

In the suggested version, we're saying Ansible can orchestrate advanced workflows for application deployment and system updates. But Ansible can also do more stuff.

For me this limits the "advanced workflows" that Ansible can orchestrate. Ansible is, in fact, great at orchestrating all kinds of advanced workflows. Application deployment and system updates are but two kinds of workflows so the "and more" is needed here because it would be too verbose to enumerate more. With the suggested version the "and more" tags on to the end of things that Ansible can do, which feels somewhat vague to me.

What do you think?

**Comment by tiyiprh** [comment]
Checking with the Content Designer!

**Comment by kaedward** [comment]
@tiyiprh @oraNod Thanks for explaining this so thoroughly! I think the "and more" in the original version threw me off. Could we use semicolons here to separate the items? 

"Configure most operating systems; deploy software; and orchestrate advanced workflows to support application deployment, system updates, and more!

**Comment by oraNod** [comment]
@kaedward Thanks for the suggestion. I'm not really sure about the semicolons. That might throw some people off, especially non-native speakers. Let's park the wording updates for now please. We're going to open this site up to the community and ask for feedback - with particular focus on wording - in the next couple of days. I'll ping you if we get any suggestions and we can figure things out in the pull request, as is tradition.

**Comment by oraNod** [comment]
@tiyiprh Great suggestion with the patternfly style dropdown menu. That should be in place with PR https://github.com/ansible-community/community-website/pull/214

Please take a look there so we can close this issue. Thanks!

**Comment by tiyiprh** [comment]
Is the "Configure" sentence and the "Learn more" bold? Also, I didn't notice this before, but is there a reason the "pip install ansible" is in a different font?

**Comment by oraNod** [comment]
@tiyiprh Here are the settings for those fonts:

"Automation powered by people": 2.25rem (36px), weight = 600, text-decoration = solid

"Configure" sentence: 1.25 rem (20 px), weight = 500, text-decoration = solid

"Learn more": 1.125rem (18px), weight = bold

**Comment by oraNod** [comment]
"pip install ansible" is wrapped in `<code>` tags so uses a monospace font instead of the Red Hat display/text. that's usually the convention for any text that goes into the terminal.

**Comment by tiyiprh** [comment]
@oraNod For "Configure" and "Learn more" would it be possible to make them the same weight? Maybe something like 400 instead of 500?

**Comment by tiyiprh** [comment]
@oraNod I was thinking either 400 or 300 as that would help with the visual hierarchy in this area as the "Automation" should be the main text.

**Comment by oraNod** [comment]
@tiyiprh How about we go with `500` so we keep it consistent with the anchor links on the hompage ("Get started", "Subscribe to Bullhorn", "Learn about Platform")

The "Learn more" on the banner page is an anchor and I've found that a higher value than `400` (which is normal) helps with accessibility. So my thinking has been to make all the anchor text the same weight.

Please take a look at the preview link here and let me know what you think: https://ansible-community-website--245.org.readthedocs.build/en/245/#

**Comment by tiyiprh** [comment]
@oraNod I think what is on this build looks good!

**Comment by oraNod** [comment]
Thanks @tiyiprh I'll close this issue and merge those changes.
