### ISSUE TITLE
Middle navigation updates

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#180]
**NAVIGATION section updates:**

- The navigation should be 100% width (fixed in [PR-169](https://github.com/ansible-community/community-website/pull/169)) but the content should stay centered like the rest of the body. The "Why Ansible" should be left justified to the "Why Ansible" section header and the "Events" should be right justified to the right most Ecosystem card.
<img width="1728" alt="Screenshot 2023-09-21 at 3 29 08 PM" src="https://github.com/ansible-community/community-website/assets/98424339/84beab32-521e-4518-a5a5-d2f69b6c564a">

- The text RH Display and should be a font size of 20 px / medium
- The width of the hover for the navigation should be fixed based on the longest item
- Icon color fixed in [PR-169](https://github.com/ansible-community/community-website/pull/169)
- I'm not sure if this is too complicated but I used a bounding box of 40x40 px for the icons to help make sure the icons would fit and it would be consistent for each section. The actual icon sizes might be different. The bounding box should be 16 px from the text. And the text should be centered vertically to the bounding box/icon.
<img width="1088" alt="Screenshot 2023-09-21 at 4 00 49 PM" src="https://github.com/ansible-community/community-website/assets/98424339/fa2ce679-5a61-4ae7-9905-c85fb18fcc44">

-Each navigation item should have a 32 px padding on top and bottom of the navigation bar

Updated Marvel: https://marvelapp.com/prototype/8bgeig6

**Comment by mabashian** [comment]
I think the font stuff has already been addressed.  It looks like the body is using Red Hat Text and the headers are using Red Hat Display.  cc @oraNod to confirm.

**Comment by oraNod** [comment]
@mabashian Yes, that's correct. The font stuff has been addressed. Thanks

**Comment by oraNod** [comment]
Merged https://github.com/ansible-community/community-website/pull/211 and will close this issue. Thank you @tiyiprh and @mabashian
