### ISSUE TITLE
Why Ansible section updates

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#181]
**WHY ANSIBLE section updates:**

- There should be 40 px of padding from the navigation to the header (icon + section title)
- Similar to the navigation - bounding box of 40x40 px with icon fitting inside. To make sure all the headers are left justified and to avoid additional padding, the icon will be left justified to the bounding box. Bounding box to header is 16 px. Text is RH Display with font size of 32 / medium. Text should be vertically centered to the bounding box and icon.
<img width="440" alt="Screenshot 2023-09-21 at 3 59 21 PM" src="https://github.com/ansible-community/community-website/assets/98424339/26a8a5b0-9176-45be-aaaf-3d172eff238a">

- There should be 24 px of padding from the header to the subtext
- There should be 24 px of padding between each paragraph
- Paragraph headers should have a font size of 18 px / bold using RH Text
- Body of the section should generally be RH Text with a font size of 18 / regular unless specified
- Pending #101 - First sentence should be updated to: "Working in IT, you're likely doing the same tasks over and over. Ansible allows you to solve problems once, then automate solutions moving forward."
- Pending #101 - Second paragraph under paragraph heading should be updated to: "Every business is a digital business. Technology is your innovation engine, and delivering your applications faster helps you win. Historically, that required a lot of manual effort and complicated coordination. Now, there’s Ansible - the simple, yet powerful IT automation engine that thousands of companies are using to drive complexity out of their environments and accelerate DevOps initiatives."
- Pending #101 - Third/fourth paragraphs under paragraph heading should be updated to : "No one likes repetitive tasks. With Ansible, IT admins can begin automating away the drudgery from their daily tasks. Automation frees admins up to focus on efforts that help deliver more value to the business by speeding time to application delivery, and building on a culture of success. Ultimately, Ansible gives teams the one thing they can never get enough of: time. 
Ansible is a simple automation language that can perfectly describe an IT application infrastructure. It’s easy to learn, self-documenting, and doesn’t require a grad-level computer science degree to read. Automation shouldn’t be more complex than the tasks it’s replacing."
- Padding from paragraph to button is 24 px
- Padding from button to "Back to top" is 16 px
- Padding from "Back to top + arrow" to next section is 40 px

Mockup:
<img width="407" alt="Screenshot 2023-09-26 at 10 24 21 AM" src="https://github.com/ansible-community/community-website/assets/98424339/9a7a282d-a21e-4f1d-ad29-b65ee0c7f52e">

Updated Marvel: https://marvelapp.com/prototype/8bgeig6

**Comment by tiyiprh** [comment]
Actual content may changed depending on https://github.com/ansible-community/community-website/issues/101

**Comment by oraNod** [comment]
Thanks again @tiyiprh I'm going to close this as we should have everything done. We're going to take it to the community to get feedback on the wording so let's see what comes of that and revisit.
