### ISSUE TITLE
Ecosystem section updates

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#182]
**ECOSYSTEM section updates:**

- This section should have a grey background black-200 #F0F0F0
- There should be 40 px to the section header
- The section header should follow the previous section: Similar to the navigation - bounding box of 40x40 px with icon fitting inside. To make sure all the headers are left justified and to avoid additional padding, the icon will be left justified to the bounding box. Bounding box to header is 16 px. Text is RH Display with font size of 32 / medium. Text should be vertically centered to the bounding box and icon.
- "View more + arrow" should be right justified and vertically centered to the header section. (fixed in [PR-168](https://github.com/ansible-community/community-website/pull/168))
- There should be 24 px of padding from the header to the subtext
- Subtext should be using RH Text and have a font size of 18 / regular
- There should be 24 px from the subtext to the cards
- There should be 32 px between the cards (side to side / top to bottom)
- From the bottom of the card to the "Back to top" should be 16 px of padding
- From the "Back to top" to the next section should be 40 px

Mockup:
<img width="812" alt="Screenshot 2023-09-22 at 4 48 04 PM" src="https://github.com/ansible-community/community-website/assets/98424339/8c94684f-ca86-4f86-ad8c-2438c3838829">

**CARDS:**

- There should be 32 px all around the content to the card
- The card title should be RH Display with a font size of 20 px / medium
- There should be 16 px of padding from the card title to the subtext
- The subtext should be RH Text with font size of 16 px / regular
- The padding between the subtext and bounding box of the icon should be 24 px
- The icons should have a bounding box of 150x150 px and the icons should fit within the box
- The "Learn more" should be a link text with arrow and 32 px from the bottom of the card

Mockup:
<img width="489" alt="Screenshot 2023-09-22 at 4 49 18 PM" src="https://github.com/ansible-community/community-website/assets/98424339/8707f77e-55cb-4fbb-b873-87d2a0cfad7a">

Updated Marvel: https://marvelapp.com/prototype/8bgeig6

**Comment by insectengine** [comment]
Changes in this PR:
https://github.com/ansible-community/community-website/pull/209
