### ISSUE TITLE
Community section updates

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#185]
**COMMUNITY section updates:**

- There should be 40 px to the section header
- The section header should follow the previous section: Similar to the navigation - bounding box of 40x40 px with icon fitting inside. To make sure all the headers are left justified and to avoid additional padding, the icon will be left justified to the bounding box. Bounding box to header is 16 px. Text is RH Display with font size of 32 px / medium. Text should be vertically centered to the bounding box and icon.
- There should be 24 px of padding from the header to the subtext
- The subtext should be RH Text with a font size of 18 px / regular
- There should be 24 px of padding from the subtext to the row of icons
- The icons should be 40x40 px (matching the icons in the header section)
- There should be 8 px of padding from the icon to the icon title
- The icon title should be RH Text with a font size of 16 px / regular
- The hover interaction is being worked on in [PR-169](https://github.com/ansible-community/community-website/pull/169)
- The padding from the icon row to the "Back to top" should be 16 px of padding
- From the "Back to top" to the next section should be 40 px

Mockup:
<img width="527" alt="Screenshot 2023-09-26 at 10 31 07 AM" src="https://github.com/ansible-community/community-website/assets/98424339/9bbf85af-54ea-40d5-856e-3c28e38cdb66">

Updated Marvel: https://marvelapp.com/prototype/8bgeig6

**Comment by oraNod** [comment]
@tiyiprh Thanks for creating this issue. Can you please do a final check and let me know if there's anything outstanding changes?
