### ISSUE TITLE
Subscribe to Bullhorn section updates

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#186]
**Subscribe to Bullhorn section updates:**

- The background color of this section should be #5CBEC1
- There should be 40 px to the header
- The header should be centered using RH Display with a font size of 32 px / medium
- There should be 24 px of padding from the header to the subtext
- The subtext should be updated to: "The Bullhorn is a weekly newsletter full of the Ansible Community's latest news and updates. You can unsubscribe at any time."
- The subtext should be using RH Text with a font size of 18 px/ medium
- There should be 24 px of padding from the subtext to the input field
- The input field should be updated to: "Insert Email address here" 
- There should be 24 px of padding from the input field to the "Subscribe" button
- The input field + button should expand the full width of the subtext (being worked on in [PR-175](https://github.com/ansible-community/community-website/issues/175)
- There should be 40 px of padding from the input field + button to the bottom of the section
- The bullhorn should have 8 px of padding from the top and bottom of the section

Mockup:
<img width="502" alt="Screenshot 2023-09-26 at 10 37 20 AM" src="https://github.com/ansible-community/community-website/assets/98424339/00a82829-6dd9-4eaa-8a6c-012fab222767">

Updated Marvel: https://marvelapp.com/prototype/8bgeig6

**Comment by oraNod** [comment]
@tiyiprh Hey on this one I noticed you have `#5BBDBF` for the colour while `5cbec1` is used for the official community "pool" colour. This comes from the brand guidelines. Should we really deviate from that?

@cybette What are your thoughts?

Thanks.

**Comment by tiyiprh** [comment]
@oraNod sorry you're correct it should be 5cbec1. I think I had originally just color matched it from an image since I didn't have the hex codes and forgot to update it once I got the hex code. I'll adjust my comment

**Comment by oraNod** [comment]
@tiyiprh I've made most of these changes in PR #198 

For the font sizes we're using `rem` because it's a bit more responsive. I don't want to deviate from that so I think we need to convert the font sizes in your description to `rem` but I'm not sure what "font size 32 medium" corresponds to. Is there any way you can specify that in rem? Even if you could let me know the px I could figure out the rem value. Thanks!

**Comment by oraNod** [comment]
Thanks again @tiyiprh I've added font sizes in `rem` with https://github.com/ansible-community/community-website/issues/199

**Comment by oraNod** [comment]
@tiyiprh Another thing to point out here. I disagree with the "Insert Email address here" update. "Email" isn't a proper noun and should not be capitalized.

**Comment by oraNod** [comment]
Oh and 24px of padding between the input field and the "Subscribe" button is too much. It pushes the button out towards the right. It was at 6px before but I've increased it to 12px. It's much better for responsiveness imo.

**Comment by tiyiprh** [comment]
What about 16 px? I think the guidance from the RH Design System is to go by pixels of 4
https://ux.redhat.com/foundations/spacing/

**Comment by oraNod** [comment]
12 px

![image](https://github.com/ansible-community/community-website/assets/32749632/f6bbf99d-e236-4aad-9172-c105a2009270)

16 px

![image](https://github.com/ansible-community/community-website/assets/32749632/d014faa7-06aa-4967-b3bc-460bb265cbee)

24 px

![image](https://github.com/ansible-community/community-website/assets/32749632/14b78e97-a0ee-49e5-93b0-b5e3457f4329)

**Comment by oraNod** [comment]
12 is still divisible by 4 so I don't think that's really a deviation from the RH design system. Anything over that and it feels like too much imo.

**Comment by oraNod** [comment]
Here's what it looks like with 8px of spacing:

![image](https://github.com/ansible-community/community-website/assets/32749632/7bbb1bf7-1e82-458b-88e2-74c0b16399dc)

**Comment by cybette** [comment]
12px looks the best to my untrained eyes, 16px is fine as well.
