### ISSUE TITLE
Blog section updates

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#187]
**BLOGS section updates:**

- There should be 40 px of padding to the header
- The section header should follow the previous section: Similar to the navigation - bounding box of 40x40 px with icon fitting inside. To make sure all the headers are left justified and to avoid additional padding, the icon will be left justified to the bounding box. Bounding box to header is 16 px. Text is RH Display with font size of 32 / medium. Text should be vertically centered to the bounding box and icon.
- "View more + arrow" should be right justified and vertically centered to the header section. (fixed in [PR-168](https://github.com/ansible-community/community-website/pull/168))
- There should be 24 px of padding from the header to the subtext
- The subtext should be using RH Text with a font size of 18 px / regular
- There should be 24 px of padding from the subtext to the row of blog posts
- Some blog post work being done in [PR-165](https://github.com/ansible-community/community-website/pull/165)
- There should be a fixed width and height for each blog post and 32 px of padding between each
- For each blog post, there should be a fixed height for each element of the post as well based off the longest one (each element of the blog post should line up horizontally to each other)
- There should be either a generic image or the image from the actual post itself (this may need some more work depending on what is feasible in the code)
- There should be 24 px of padding from the image to the author/date text
- The author/date should be using RH Text with a font size of 14 px / Medium, in caps, and in the color #004080
- From the author/date text to the title of the blog should be 4 px padding
- The title should be using RH Text with a font size of 20 px / Medium
- The title should be clickable to take the user to the blog post page
- There should be 16 px of padding from the row of blog posts to the "Back to top" button
- There should be 40 px of padding from the "Back to top" to the next section

Mockup:
<img width="503" alt="Screenshot 2023-09-26 at 10 43 02 AM" src="https://github.com/ansible-community/community-website/assets/98424339/f9b34609-4b75-4be4-a1ec-aa857cb22dc3">

Updated Marvel: https://marvelapp.com/prototype/8bgeig6

**Comment by oraNod** [comment]
Thanks @tiyiprh I think we can go ahead and close this one. I believe everything here should be sorted now and we can follow up on the blog graphics as part of https://github.com/ansible-community/community-website/issues/194
