### ISSUE TITLE
Events section updates

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#189]
**EVENTS section updates:**

- There should be 40 px to the section header
- The section header should follow the previous section: Similar to the navigation - bounding box of 40x40 px with icon fitting inside. To make sure all the headers are left justified and to avoid additional padding, the icon will be left justified to the bounding box. Bounding box to header is 16 px. Text is RH Display with font size of 32 / medium. Text should be vertically centered to the bounding box and icon.
- There should be 24 px of padding from the header to the subtext
- The subtext should be using RH Text with a font size of 18 px / Regular
- Based on the number of events we want to show, we should follow a similar format to the blogs section in which there is a fixed width/height for each element of the post based off the longest one and each element of the event should line up horizontally to each other
- There should be 96 px of padding between the events if there are only two events and 32 px of padding between the events if there are three events.
- There should be an image of the event and 16 px of padding from the image to the title of the event
- The event title should be RH Text with a font size of 20 px / Medium
- The event title should be clickable to take the user to the event details page
- There should be 8 px of padding to the event description
- The event description should be RH Text with a font size of 16 px / Regular
- There should be 8 px of padding to the event date/location
- The event date/location should be RH Text with a font size of 16 px/ Medium
- From the row of events to the "Back to top" button should be 16 px of padding
- From the "Back to top" to the next section should be 40 px of padding

Mockup:
<img width="501" alt="Screenshot 2023-09-26 at 10 48 20 AM" src="https://github.com/ansible-community/community-website/assets/98424339/0dce8a57-6daf-4911-9fe0-06f0b61968c3">

Updated Marvel: https://marvelapp.com/prototype/8bgeig6

**Comment by oraNod** [comment]
@tiyiprh Let's maybe close this one and if there's anything else left to do, please add a comment to https://github.com/ansible-community/community-website/pull/210

**Comment by tiyiprh** [comment]
Adding more comments to #210
