### ISSUE TITLE
Masthead should be the same across all the pages

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#191]
The masthead should be the same across all pages within the website for consistency and cohesiveness. The current implementation of the "Latest posts" seems to follow this. However there are some differences, such as the background color and where the Ansible logo + Community sit and how far out to the right the other links/button are.

Current homepage:
<img width="1726" alt="Screenshot 2023-09-22 at 3 59 02 PM" src="https://github.com/ansible-community/community-website/assets/98424339/615c061b-25ca-4c40-87c4-c3a4904efeef">

Current Latest posts:
<img width="1728" alt="Screenshot 2023-09-22 at 3 59 16 PM" src="https://github.com/ansible-community/community-website/assets/98424339/48ae0c87-8e13-46b6-b914-9d559808f7b7">

**Comment by tiyiprh** [comment]
Hi @oraNod, it looks like some of the mastheads on the secondary Blog pages under the dropdown got updated but there are still a few updates that need to be made.

The "Latest posts," "Tags," "Post Archive" pages need the masthead background color to be updated to #5BBDBF (the Ansible cyan color). This will help in the cohesiveness of keeping all the pages in a similar style within this Ansible community landing page.

Below are a few mockups of what the other pages should look like:

The "RSS feed" page needs to updated as well:
-the background color needs to be updated as above and the following links should appear on this page as well
-the body text should match the other pages under "Blogs" 
![RSS Feed](https://github.com/ansible-community/community-website/assets/98424339/970fb39d-50dd-49be-a55e-5f35b5e09add)

The "Ansible community forum" page:
-the background color should be updated to the cyan and the home/search icons should be updated to black
-ideally we'd want those icons to be text but if that can't be done and the icon colors cannot change, we should at least update the logo to match the other pages
![Hi-Fi Landing Page-Forum](https://github.com/ansible-community/community-website/assets/98424339/4ccf3f6a-c06d-458d-98dd-94f248b84d8d)

The "Documentation" page:
-why is the blogs section in documentation different from the blogs in the current implementation?
-the background color should be updated to the cyan and the following links on the home page should still appear in addition to the links from the documentation page
![Hi-Fi Landing Page-Documentation](https://github.com/ansible-community/community-website/assets/98424339/f84436af-25ed-4f14-b599-2f2dd0e47ba6)

**Comment by oraNod** [comment]
Thanks @tiyiprh Rather than reopening this issue, I would prefer to break it out into some separate issues:

- New issue in this repo for the blog masthead.
- New issue in https://github.com/ansible/docsite for the documentation pages

@GregSutcliffe Where should issues for the Ansible community forum go?

**Comment by tiyiprh** [comment]
@oraNod sounds good, I can create new issues for each page
