### ISSUE TITLE
Events graphics

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#193]
Create a set of reusable and interchangeable SVG images for the following event types:

- Ansible community day
- Ansible contributor summit
- Ansible meetup

**Comment by cybette** [comment]
I like this idea.

It's mainly:
- Ansible Community Day
- Ansible Contributor Summit
- Ansible meetup

Red Hat Summit, AnsibleFest and others (like FOSDEM) are their own events and have their own branding, our community events are usually part of or adjacent to them (e.g. Ansible Community Day at Red Hat Summit, Ansible Contributor Summit at CfgMgmtCamp).

**Comment by oraNod** [comment]
@tiyiprh Hi, any chance you could take a look at this one please? If we could get three svg graphics for the three main event types that would be great. Thanks!

**Comment by tiyiprh** [comment]
@oraNod are you looking for an image or an icon similar to the ones we're using for each section header?

**Comment by oraNod** [comment]
@tiyiprh an image would be nice. I have a set of svg images in mind that we could swap out and reuse for the events section to make life easy to and to make things consistent. if it would help I could take a first pass.

**Comment by tiyiprh** [comment]
Sure! That would be great!

**Comment by oraNod** [comment]
@tiyiprh Hi, I've added some graphics to the linked PR if you could take a look please. I think we've got a bit of time to come up with some better reusable graphics but I want to at least have some decent looking svgs in place before we launch.
