### ISSUE TITLE
Blog Graphics

### ISSUE THREAD

**Issue by GregSutcliffe** [ansible-community/community-website#194]
In #165 we did not come to agreement on how to handle the images that head up the blog posts on the homepage. I merged it to keep the rest of the design work moving, but we should resolve this.

I'm for keeping images and ensuring blog posts have an appropriate image set, I think it makes the page less wall-o-text-y

**Comment by oraNod** [comment]
@GregSutcliffe What's the story with the "MVP" label?

**Comment by GregSutcliffe** [comment]
On 27/09/2023 11:14, Don Naro wrote:
> @GregSutcliffe <https://github.com/GregSutcliffe> What's the story with 
> the "MVP" label?

Umm, I think I was trying to say "this needs to be decided before 
launch". We might have some overlapping labels ;)

**Comment by oraNod** [comment]
I think "blocker" communicates that effectively. I'm going to get rid of the MVP label because that was something we got stuck on before, same thing with "alpha". Cheers.

**Comment by tiyiprh** [comment]
I agree that it would be nice to include images. For blogs/posts that have an image included maybe we can use those and come up with a few generic images for posts that do not have an image that we can surface up and just cycle through those.  What do you think? We'd have make sure the images are the same fixed width/height so the blog section can look spaced out correctly.

**Comment by tiyiprh** [comment]
Here are some generic images we can potentially use for the blogs section:

**Comment by oraNod** [comment]
Thanks @tiyiprh

**Comment by oraNod** [comment]
@GregSutcliffe FYI the post template added in https://github.com/ansible-community/community-website/pull/302 should let us handle this

**Comment by tiyiprh** [comment]
@oraNod What is the status on this issue? Are we able to add graphics to the blog posts area or is that something that will come later?

**Comment by oraNod** [comment]
@tiyiprh Hi, there's a bit more work we need to do on the post templates to add the generic graphics to the blog. I've marked this as a future enhancement for now. It'll come later but hopefully not too much later.

**Comment by oraNod** [comment]
Closing this one now that the blog band on the homepage has been removed. We can revisit if needed.
