### ISSUE TITLE
Make sure the final site works with JS disabled

### ISSUE THREAD

**Issue by GregSutcliffe** [ansible-community/community-website#195]
Right now it appears that RTD *requires* JS to render at all (I'm guessing it has to do with the switcher in the bottom right)

I'd like to keep JS to a minimum so that site *mostly* works with it disabled - obviously some small stuff will break, but we *will* have people disabling JS (and often because of accessibility).

**Comment by oraNod** [comment]
@GregSutcliffe I think we're OK here. I've tried using the site with JS disabled and the only thing that doesn't work is the copy to clipboard for "pip install ansible". You can still copy that manually though and the text displays so I don't think it's an issue. Should we go ahead and close this as it is a blocker?
