### ISSUE TITLE
Tooltips should be using CSS with arrow

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#196]
Tooltips should be using CSS not the default browser generated ones. The one we should be using is the one with the arrow as found here: https://www.w3schools.com/css/css_tooltip.asp

**Comment by oraNod** [comment]
@mabashian Please feel free to take this one. I sent an invite but it's still pending so I can't seem to assign you.

**Comment by oraNod** [comment]
As discussed during the hackathon I'll remove titles from buttons. https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title#accessibility_concerns
