### ISSUE TITLE
Consider using different font family

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#204]
Follows up on https://github.com/ansible-community/community-website/issues/199

Current site uses Red Hat fonts. Should we use a different font family to help make the distinction between community and Red Hat more apparent?

**Comment by oraNod** [comment]
@GregSutcliffe and @tiyiprh Any thoughts on this one? A good alternative seems to be `font-family: 'Open Sans', Arial, sans-serif;`

I'll submit a PR when #199 gets merged and we can take a look.

**Comment by GregSutcliffe** [comment]
Apart from "don't us comic sans" I am the worst person to advise on this stuff, I'll defer to @tiyiprh and others

**Comment by tiyiprh** [comment]
My thought is that we should try to keep as much as we can to the RH standard as there is a guide and that makes it a bit easier when creating a website. I'm not sure if the font will make much of a distinction or if the users notice that but maybe we can see if there is any feedback from the community about that and then take a look at potentially changing it. What do you all think about that?

**Comment by GregSutcliffe** [comment]
I'm happy to wait and see if it's commented on, sure.
