### ISSUE TITLE
Move community logos and assets to the associated GitHub repository

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#205]
Need to determine the best place to put community logos and other assets similar to https://www.ansible.com/logos

Also need to ensure that there is an appropriate place for the product logos on `redhat.com` so that we do not need to retain or maintain them as part of the community site.

**Comment by cybette** [comment]
Product logos are available at https://www.redhat.com/en/about/brand/standards/product-logos (with restricted access, but that's the preferred way). So we don't have to maintain that.

As for where to put Communtiy logos, would the forum be a better place? or consolidate everything in https://github.com/ansible/logos/ ?

**Comment by wbentley15** [comment]
Personally I think it would be best to consolidate them to https://github.com/ansible/logos/.  That will be one less page to maintain.

**Comment by oraNod** [comment]
@cybette and @wbentley15 I've pulled down all the images from the logos page and migrated to that repository. I also updated the README with the details about logo usage.

**Comment by cybette** [comment]
Sounds good, thanks @oraNod !

**Comment by oraNod** [comment]
@cybette Thanks! That PR was merged. Usage guidelines are in the readme at https://github.com/ansible/logos#usage-guidelines and the logos are now available from https://github.com/ansible/logos 

Going to close this as done. Cheers.
