### ISSUE TITLE
Bullhorn-subscribe band responsiveness impacted by font increase

### ISSUE THREAD

**Issue by GregSutcliffe** [ansible-community/community-website#206]
Looks like after #198 we now get some issues at around 800px width with text overlapping the image.

**Comment by oraNod** [comment]
Thanks @GregSutcliffe I'll add the hackathon label and hopefully the css experts can fine tune those global font sizes to play nicely with the responsive breakpoints.

**Comment by oraNod** [comment]
@GregSutcliffe #200 should resolve this issue. Would you mind taking a look at the latest version and closing if you agree? Thanks.
