### ISSUE TITLE
Website responsiveness at different screen sizes

### ISSUE THREAD

**Issue by michellemacrh** [ansible-community/community-website#219]
## Description
I took a look at the website on my phone as well as resizing my browser screen and noticed a few things that could be improved in terms of responsiveness. Not sure what the priority is in terms of responsiveness but might be worth doing a pass to ensure responsive at various screen sizes. 

## Screenshot
![Responsiveness on Mobile](https://github.com/ansible-community/community-website/assets/141345897/88455e10-2584-4d50-9396-f000d8cb0627)

**Comment by oraNod** [comment]
This is caused by the readthedocs widget. For issues related to responsiveness please build locally and use something like the mozilla responsive design tool. Thanks.
