### ISSUE TITLE
Consider limiting width of content especially on large screens

### ISSUE THREAD

**Issue by michellemacrh** [ansible-community/community-website#220]
## Description
It might be helpful to reduce the width of the content, especially on large screen sizes. 

I believe it's best practice for readability to limit character/line width to 80 characters. [WCAG Guidelines](https://www.w3.org/WAI/WCAG21/Understanding/visual-presentation.html#:~:text=Width%20is%20no%20more%20than,larger%20than%20the%20line%20spacing.)

I've included a screenshot below that shows the top section limited to 80 characters and the bottom section with the original width.

## Screenshot
![Screenshot 2023-09-29 at 09 33 56](https://github.com/ansible-community/community-website/assets/141345897/e903571d-e8cc-4bef-b8b1-d86116039981)

**Comment by oraNod** [comment]
Relates to https://github.com/ansible-community/community-website/issues/9

Thanks for the issue. While it's not ideal we do have some accessibility issues while the site is in development, this being one of them. Please feel free to add additional comments to #9 or create new issues for any other accessibility snags you happen to find.

**Comment by oraNod** [comment]
@michellemacrh Just looking at this now. Feel free to send a PR with the change if you like. IMO it'd be ideal to set this globally somewhere like https://github.com/ansible-community/community-website/blob/20d13c4e1f2937c7d3e6fa3be5d420e13a6086cd/themes/ansible-community/sass/main.scss#L24

What would you suggest?

**Comment by michellemacrh** [comment]
I agree that setting this in one place would be ideal. However I'm not sure it's as simple as setting `max-width: 80ch` in the body tag as this will constrain the width of the whole screen.

I think each section/container would need to be considered to ensure it doesn't negatively impact the current design.

**Comment by oraNod** [comment]
Thanks for raising this issue @michellemacrh

**Comment by michellemacrh** [comment]
No problem, happy to contribute :)
