### ISSUE TITLE
Updates to events section

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#222]
https://github.com/ansible-community/community-website/pull/210#issuecomment-1739854436

Some minor updates:

- Based on the number of events we want to show, we should follow a similar format to the blogs section in which there is a fixed width/height for each element of the post based off the longest one and each element of the event should line up horizontally to each other
- The layout of each event should be: Image, title, description, date and location
- Only the event title should be clickable to take the user to the event details page (not the image or description, etc)

From current implementation:

- The area of the Nerdearla image should match the Ansible Contributor Summit so the image should either increase or be centered to have the same width/height
- The title should be under the image and be horizontally lined up together and have a fixed width/height
- The description should have a fixed width/height and be horizontally lined up together
- The date and location should be horizontally lined up together

**Comment by oraNod** [comment]
@tiyiprh Thanks for going over this. It still needed a bit of work. Hopefully it's better now and I've got the images aligned so they should always stay bounded within the div and horizontally aligned.

TBH I wasn't quite sure about the alignment for the text section. Do you have an updated marvel or screenshot of how it should look?

**Comment by oraNod** [comment]
@tiyiprh Would you mind taking a look at an update: https://ansible-community-website--223.org.readthedocs.build/en/223/#events

I've made the title and image clickable, which honestly seems a lot better to me. I also tried to get the event date and location to stay as fixed as possible. It's not perfect but I made it so the max width is 40 characters which means there will usually be about three lines on most displays.

If you resize you can still hit a point where one paragraph wraps to four lines and then the event data and location gets pushed down. Not sure there's much we can do with that other than making sure the descriptions contain roughly the same number of characters.

I'll see again in the morning. Might be a good idea to add another comment to the yaml file about keeping the descriptions similar length. That shouldn't be too hard to achieve.

**Comment by tiyiprh** [comment]
@oraNod Looks good! Thanks for making those updates!

**Comment by oraNod** [comment]
Thanks for the guidance and the review @tiyiprh
