### ISSUE TITLE
Design the docs landing page for all projects on community site

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#23]
Design the docs landing page based on personas:

- [x] use ansible/jinja2 for quick prototyping
- [x] and links from docs.ansible.com to this prototype site for community feedback
- [x] add links from prototype site to docs.ansible.com so reviewers can quickly get back to the existing site.

**Comment by Andersson007** [comment]
i think at least p.1 can be marked as done.
we're polishing the prototype now
