### ISSUE TITLE
Design a homepage for the community site

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#25]
Create a homepage for the Ansible community site that incorporates https://github.com/ansible-community/community-website/issues/20

**Comment by oraNod** [comment]
To make the homepage bands look awesome we'll need to:

- Get svg icons for Ansible features.
- Get an Ansible community banner image.
- Design user experience for navigating the homepage bands, taking in responsive behaviour and accessibility.

**Comment by oraNod** [comment]
Let's close this as complete with #40 

Now that the PR is merged we have a base design for the homepage. We can track effort to style the bands and plug in whatever elements / content as separate issues. Thanks @samccann
