### ISSUE TITLE
Middle navigation padding looks off on hover

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#253]
The padding on each section's hover on the middle navigation looks off. In a previous build it looked correct but now it looks like there is slight padding on the left and a little more padding on the right but overall not an even amount of padding like before.

Current:
<img width="348" alt="Screenshot 2023-10-04 at 10 28 51 PM" src="https://github.com/ansible-community/community-website/assets/98424339/37f28781-4fb8-40c6-8b8e-03455a0a91ea">

Previous:
<img width="305" alt="Screenshot 2023-10-04 at 10 30 20 PM" src="https://github.com/ansible-community/community-website/assets/98424339/d8b07ebc-86df-495b-8395-61517bf4d3fc">

**Comment by oraNod** [comment]
@tiyiprh I've made some changes to add an even amount of padding to the tabs. This does mean that we'll no longer be able to have the first tab left aligned with the following text, but that's how it was before so I guess it's OK.

Please take a look and verify at https://ansible-community-website--256.org.readthedocs.build/en/256/

**Comment by tiyiprh** [comment]
Looks great, thank you!
