### ISSUE TITLE
Hero section - "Learn about RH AAP" minor update

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#254]
Some updates to the hero section "Learn more about AAP" line:
-The RH logo should be the same height as the text
-The logo should be separate from the text and not clickable. Only the text itself should be clickable and have a hover state

**Comment by oraNod** [comment]
@tiyiprh Please verify changes at https://ansible-community-website--255.org.readthedocs.build/en/255/

**Comment by tiyiprh** [comment]
This looks better! Thank you for making the updates!

**Comment by oraNod** [comment]
Thanks for the additional review @tiyiprh It's great to get this level of detail. Sorry for the churn that has come from the accessibility testing.
