### ISSUE TITLE
Masthead update - Blogs section

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#271]
The "Latest posts," "Tags," "Post Archive" pages need the masthead background color to be updated to #5BBDBF (the Ansible cyan color). This will help in the cohesiveness of keeping all the pages in a similar style within this Ansible community landing page.

**Comment by oraNod** [comment]
I've broken the details about the masthead and footer for the RSS feed to a separate issue. That will require some investigation given it's xml not html.
