### ISSUE TITLE
Masthead update - Documentation section

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#273]
The "Documentation" page:
-why is the blogs section in documentation different from the blogs in the current implementation?
-the background color should be updated to the cyan (#5BBDBF) and the following links on the home page should still appear in addition to the links from the documentation page
![Hi-Fi Landing Page-Documentation](https://github.com/ansible-community/community-website/assets/98424339/f84436af-25ed-4f14-b599-2f2dd0e47ba6)

**Comment by oraNod** [comment]
I've created a corresponding issue and pull request for the `ansible/docsite` repository where the actual changes need to be merged. I'll close this issue now and we can track the effort in the other repo. Thanks.
