### ISSUE TITLE
Ecosystem section - Learn more hover state error

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#274]
In the latest build, I noticed in the Ecosystem section that the hover area for the "Learn more" is quite large, going past the "Learn more" itself, about the width of the description text of the project. It should only hover on the "Learn more"
<img width="1572" alt="Screenshot 2023-10-06 at 2 45 33 PM" src="https://github.com/ansible-community/community-website/assets/98424339/ceedaf81-58a0-49f5-8911-e1e38183b4b5">

**Comment by oraNod** [comment]
@tiyiprh Well spotted. Thanks for catching this. I believe it's fixed in #266 

Please verify here: https://ansible-community-website--266.org.readthedocs.build/en/266/

**Comment by tiyiprh** [comment]
@oraNod Thank you!
