### ISSUE TITLE
Port GalaxyNG blog post to .md

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#276]
In an effort to move important community blog posts from Ansible.com to the new website, we want to take https://www.ansible.com/blog/new-ansible-galaxy and convert it to .md here in this repository.  The steps to do this are:

- [ ] Create a set of folders under `/posts` that have:
  * `<year/month/day>`  
- [ ] convert the content to .md with a filename that matches the blog title, all lower-case with hyphens between each word.
- [ ] copy each image to a new folder `/images/posts/<imagename>`, where `<imagename>` is the name of the .md file.
- [ ] Add appropriate metadata at the top of the .md file. See example below.

So for this  blog post, the folder would be:
`posts/2023/09/23`

And the filename would be `new-ansible-galaxy.md`

There are no images in this blog post to worry about, but if there were, it would be `/images/posts/new-ansible-galaxy/foo.png` for example.

And the metadata at the top of the file would be:

```
---
title: New Ansible Galaxy
author: John Hardy
date: 2023-09-26 13:00:00
slug: new-ansible-galaxy
category: galaxy
tags: galaxy
type: text
---
```

**Comment by samccann** [comment]
This issue ON HOLD for now while the accessibility testing/improvements are worked on for the whole website. Please hold off on any PRs for now.

**Comment by samccann** [comment]
@Dule-martins - this issue would be good for a community-writer to take. Requires git knowledge.

**Comment by Dule-martins** [comment]
Sure, let me add it to the Ansible community writers board.
