### ISSUE TITLE
Keeping Fedora version up to date in the dockerfile

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#294]
https://github.com/ansible-community/community-website/blob/2cf69728fe0ea9132fdf23eab1a2f21a9f0cd7e0/Dockerfile#L15

Find a way to automatically keep the Fedora version (and python) up to date in the dockerfile. A couple of suggestions from misc:

- add a CI test to verify the version is not EOL
- use FROM scratch + a 3rd container to fetch caddy binary

See https://github.com/ansible-community/community-website/pull/288#discussion_r1385025964

**Comment by gotmax23** [comment]
I think GitHub's builtin dependabot can do this.
