### ISSUE TITLE
Adjust links on landing page

### ISSUE THREAD

**Issue by wbentley15** [ansible-community/community-website#296]
Wanted to add a note to review all the links on the landing page and make sure they point to the correct pages on or off ansible.com domain.

**Comment by oraNod** [comment]
@wbentley15 All the links on the landing / homepage are set in the `data/homepage.yaml` file. For example: https://github.com/ansible-community/community-website/blob/e579b46ec50312a0f14020afbbc97c1a32b4f789/data/homepage.yaml#L161

Note that any links to `redhat.com` point only to that `platform.home` url as per the directive from the marketing folks. We could remove the `platform.use_cases` url. It does not seem to be used. Do we need to go through any sort of sign off process before closing this?

Or could I misunderstand the purpose a little? Maybe we could use this issue to verify that all the urls for the secondary pages match what you've outlined in https://github.com/ansible-community/community-website/issues/285 before we go live?

**Comment by oraNod** [comment]
I feel confident we've addressed this issue and can close. Thanks.
