### ISSUE TITLE
Which license to choose for this repository ?

### ISSUE THREAD

**Issue by Spredzy** [ansible-community/community-website#3]
Hello all,

I think title says it all. We need to decide what is the proper issue for this project ideally before taking any contribution.

In an earlier chat CC-BY-SA (https://creativecommons.org/licenses/by-sa/4.0/) was brought up as a possibility.

What is the group opinion on that ?

**Comment by cybette** [comment]
@anweshadas please contact RH legal for comment

**Comment by cybette** [comment]
Licence CC BY-SA 4.0 added https://github.com/ansible-community/community-website/pull/2

Closing issue.
