### ISSUE TITLE
Collection Spotlight banner and supporting pages

### ISSUE THREAD

**Issue by wbentley15** [ansible-community/community-website#303]
Wanted to propose the idea of having a "Featured Collections" or "Collection Spotlight" banner added to the homepage OR a link to a landing page where community member can feature upstream collections.  Placeholders for each collection page can incorporate links to documentation, code repo and any other details.

**Comment by oraNod** [comment]
That's a nice idea, might be a good one for the forum to gauge the community and get their input on how we decide on which collections get featured and why. I can try to rustle up a mockup or something in a PR to get the ball rolling. Might also interest @tiyiprh

**Comment by tiyiprh** [comment]
@oraNod I can put together something as well!

**Comment by tiyiprh** [comment]
@oraNod Can you provide some screenshots of what the current upstream collections pages/details look like?

**Comment by tiyiprh** [comment]
Here is the landing page with a "Featured collections" section. Is the thought that if the user clicks on a collection, they would be brought to that collection's details on Galaxy? Similarly, if they were to click "View more" in this new "Featured collections" section, they would be brought to the Collections landing page in Galaxy?

Let me know what you think and if I'm on the right track! Thanks!

![Hi-Fi Landing Page-Updated 11 20](https://github.com/ansible-community/community-website/assets/98424339/68dfa586-204c-43d6-a927-b330fad10059)

**Comment by oraNod** [comment]
@tiyiprh Hey apologies for the delay I was abroad on PTO. That looks fantastic to me and right on the money (apart from the fact the community collections aren't provided by Red Hat). You can see community collections here: https://galaxy.ansible.com/ui/collections/

And, yes, that sounds like the right behaviour to me. Click on a collection, go to Galaxy.

**Comment by tiyiprh** [comment]
No worries! Awesome, then I think just pulling in collections from Galaxy into this "Featured collections" bar would do the trick! This bar would just house the featured collections and once they click on it, they land on the details in the Galaxy UI and can continue to browse things in that UI.

**Comment by wbentley15** [comment]
As long we have control over which collections will be hightlighted/featured...yes I would say you are spot on!  Thanks again for designing it!
