### ISSUE TITLE
[Blog] Port Event-Driven Ansible blog post to .md

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#305]
In an effort to move important community blog posts from Ansible.com to the new website, we want to take https://www.ansible.com/blog/event-driven-ansible-is-here and convert it to .md here in this repository.  The steps to do this are:

- [ ] Create a set of folders under `/posts` that have:
  * `<year/month/day>`  
- [ ] convert the content to .md with a filename that matches the blog title, all lower-case with hyphens between each word.
- [ ] copy each image to a new folder `/images/posts/<imagename>`, where `<imagename>` is the name of the .md file.
- [ ] Add appropriate metadata at the top of the .md file. See example below.

So for this  blog post, the folder would be:
`posts/2023/05/23`

And the filename would be `event-driven-ansible-is-here.md`

Images go to  `/images/posts/event-driven-ansible-is-here/foo.png` for example.

And the metadata at the top of the file would be:

```
---
title: Event-Driven Ansible is Here
author: Joe Pisciotta
date: 2023-05-23 13:00:00
slug: event-driven-ansible-is-here
category: event-driven-ansible
tags: event-driven-ansible
type: text
---
```

**Comment by leogallego** [comment]
Adding tags related to the release/announcement of EDA

```
category: event-driven-ansible
tags: event-driven-ansible, release, announcement, eda
```
