### ISSUE TITLE
[Blog] Port Getting Started with Event-Driven Ansible blog post  to .md

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#306]
In an effort to move important community blog posts from Ansible.com to the new website, we want to take https://www.ansible.com/blog/getting-started-with-event-driven-ansible and convert it to .md here in this repository.  The steps to do this are:

- [ ] Create a set of folders under `/posts` that have:
  * `<year/month/day>`  
- [ ] convert the content to .md with a filename that matches the blog title, all lower-case with hyphens between each word.
- [ ] copy each image to a new folder `/images/posts/<imagename>`, where `<imagename>` is the name of the image file.
- [ ] Add appropriate metadata at the top of the .md file. See example below.

So for this  blog post, the folder would be:
`posts/2022/10/19`

And the filename would be `getting-started-with-event-driven-ansible.md`

Images go to  `/images/posts/getting-started-with-event-driven-ansible/foo.png` for example.

And the metadata at the top of the file would be:

```
---
title: Getting Started with Event-Driven Ansible
author: Nuno Martins
date: 2022-10-19 13:00:00
slug: getting-started-with-event-driven-ansible
category: event-driven-ansible
tags: event-driven-ansible, getting-started
type: text
---
```

**Comment by leogallego** [comment]
Category looks good, adding a few tags

```
category: event-driven-ansible
tags: event-driven-ansible, getting-started, eda, ansible-rulebook, rulebooks
```
