### ISSUE TITLE
[Blog] Port Event-Driven Ansible-ChatOps blog to .md

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#307]
In an effort to move important community blog posts from Ansible.com to the new website, we want to take https://www.ansible.com/blog/event-driven-ansible-chatops-from-chat-to-action and convert it to .md here in this repository.  The steps to do this are:

- [ ] Create a set of folders under `/posts` that have:
  * `<year/month/day>`  
- [ ] convert the content to .md with a filename that matches the blog title, all lower-case with hyphens between each word.
- [ ] copy each image to a new folder `/images/posts/<imagename>`, where `<imagename>` is the name of the image file.
- [ ] Add appropriate metadata at the top of the .md file. See example below.

So for this blog post, the folder would be:
`posts/2023/09/01`

And the filename would be `event-driven-ansible-chatops-from-chat-to-action`

Images go to  `/images/posts/event-driven-ansible-chatops-from-chat-to-action/foo.png` for example.

And the metadata at the top of the file would be:

```
---
title: Event-Driven Ansible - ChatOps - From Chat to Action
author: Nuno Martins
date: 2023-09-01 13:00:00
slug: event-driven-ansible-chatops-from-chat-to-action
category: event-driven-ansible
tags: event-driven-ansible
type: text
---
```

**Comment by leogallego** [comment]
Category looks good, adding a few tags:

```
category: event-driven-ansible
tags: event-driven-ansible, chatops, rulebooks, netops, webhooks, mattermost, teams, slack, ansible-rulebook
```
