### ISSUE TITLE
[Blog] Port Kubernetes Meets Event-Driven Ansible to .md

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#308]
In an effort to move important community blog posts from Ansible.com to the new website, we want to take https://www.ansible.com/blog/kubernetes-meets-event-driven-ansible and convert it to .md here in this repository.  The steps to do this are:

- [ ] Create a set of folders under `/posts` that have:
  * `<year/month/day>`  
- [ ] convert the content to .md with a filename that matches the blog title, all lower-case with hyphens between each word.
- [ ] copy each image to a new folder `/images/posts/<imagename>`, where `<imagename>` is the name of the image file.
- [ ] Add appropriate metadata at the top of the .md file. See example below.

So for this blog post, the folder would be:
`posts/2023/03/16`

And the filename would be `kubernetes-meets-event-driven-ansible`

Images go to  `/images/posts/kubernetes-meets-event-driven-ansible/foo.png` for example.

And the metadata at the top of the file would be:

```
---
title: Kubernetes Meets Event-Driven Ansible
author: Andrew Block
date: 2023-03-16 13:00:00
slug: kubernetes-meets-event-driven-ansible
category: event-driven-ansible
tags: event-driven-ansible
type: text
---
```

**Comment by leogallego** [comment]
Category looks good (not sure on spaces vs dash though)
Adding a few tags.

```
category: event-driven-ansible
tags: event-driven-ansible, kubernetes, rulebooks, eda, ansible-rulebook
```
