### ISSUE TITLE
[Blog] Port Ansible and ChatGPT: Putting it to the test blog to .md

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#309]
In an effort to move important community blog posts from Ansible.com to the new website, we want to take https://www.ansible.com/blog/ansible-wisdom-and-chatgpt-putting-it-to-the-test and convert it to .md here in this repository.  The steps to do this are:

- [ ] Create a set of folders under `/posts` that have:
  * `<year/month/day>`  
- [ ] convert the content to .md with a filename that matches the blog title, all lower-case with hyphens between each word.
- [ ] copy each image to a new folder `/images/posts/<imagename>`, where `<imagename>` is the name of the image file.
- [ ] Add appropriate metadata at the top of the .md file. See example below.

So for this blog post, the folder would be:
`posts/2023/01/23`

And the filename would be `ansible-wisdom-and-chatgpt-putting-it-to-the-test`

Images go to  `/images/posts/ansible-wisdom-and-chatgpt-putting-it-to-the-test/foo.png` for example.

And the metadata at the top of the file would be:

```
---
title: Ansible and ChatGPT: Putting it to the test
author: Craig Brandt
date: 2023-01-23 13:00:00
slug:ansible-wisdom-and-chatgpt-putting-it-to-the-test
category: ansible-lightspeed
tags: ansible-lightspeed
type: text
---
```

**Comment by leogallego** [comment]
I think we can simplify the category to `lightspeed` here as there is no CLI command to associate it to (like for Lint or Navigator). Adding a few related tags as well

```
category: lightspeed
tags: lightspeed, ai, chatgpt, artificial intelligence, generative ai, openai, llm, vscode-ansible
```
