### ISSUE TITLE
[Blog] Port Deep dive on Ansible VScode extension to .md

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#310]
In an effort to move important community blog posts from Ansible.com to the new website, we want to take https://www.ansible.com/blog/deep-dive-on-ansible-vscode-extension and convert it to .md here in this repository.  
The steps to do this are:

- [ ] Create a set of folders under `/posts` that have:
  * `<year/month/day>`  
- [ ] convert the content to .md with a filename that matches the blog title, all lower-case with hyphens between each word.
- [ ] copy each image to a new folder `/images/posts/<imagename>`, where `<imagename>` is the name of the image file.
- [ ] Add appropriate metadata at the top of the .md file. See example below.

So for this blog post, the folder would be:
`posts/2022/04/18`

And the filename would be `deep-dive-on-ansible-vscode-extension`

Images go to  `/images/posts/deep-dive-on-ansible-vscode-extension/foo.png` for example.

And the metadata at the top of the file would be:

```
---
title: Deep dive on Ansible VScode extension
author: Ganesh Nalawade
date: 2022-04-18 13:00:00
slug:deep-dive-on-ansible-vscode-extension
category: devtools
tags: vscode-extension
type: text
---
```

**Comment by leogallego** [comment]
Adding a few tags and changing the vscode-extension to vscode-ansible for consistency

```
category: devtools
tags: vscode-ansible, ansible-language-server, ansible-lint, vscode, execution environments
```
