### ISSUE TITLE
[Blog] Port Automating Azure Infrastructure for High Availability Web Hosting with Ansible to .md

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#311]
In an effort to move important community blog posts from Ansible.com to the new website, we want to take https://www.ansible.com/blog/automating-azure-infrastructure-for-high-availability-web-hosting-with-ansible and convert it to .md here in this repository.  
The steps to do this are:

- [ ] Create a set of folders under `/posts` that have:
  * `<year/month/day>`  
- [ ] convert the content to .md with a filename that matches the blog title, all lower-case with hyphens between each word.
- [ ] copy each image to a new folder `/images/posts/<imagename>`, where `<imagename>` is the name of the image file.
- [ ] Add appropriate metadata at the top of the .md file. See example below.

So for this blog post, the folder would be:
`posts/2023/08/30`

And the filename would be `automating-azure-infrastructure-for-high-availability-web-hosting-with-ansible`

Images go to  `/images/posts/automating-azure-infrastructure-for-high-availability-web-hosting-with-ansible/foo.png` for example.

And the metadata at the top of the file would be:

```
---
title: Automating Azure Infrastructure for High Availability Web Hosting with Ansible
author: Nicolas Leiva
date: 2023-08-30 13:00:00
slug: automating-azure-infrastructure-for-high-availability-web-hosting-with-ansible
category: azure
tags: azure
type: text
---
```

**Comment by leogallego** [comment]
@samccann I would probably change the category to cloud and use tags for each for now:

```
category: cloud
tags: cloud, azure, high availability, collection, aws
```
