### ISSUE TITLE
[Blog] Port Ansible data manipulation with a Filter to .md

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#312]
In an effort to move important community blog posts from Ansible.com to the new website, we want to take https://www.ansible.com/blog/ansible-data-manipulation-with-a-filter and convert it to .md here in this repository.  
The steps to do this are:

- [ ] Create a set of folders under `/posts` that have:
  * `<year/month/day>`  
- [ ] convert the content to .md with a filename that matches the blog title, all lower-case with hyphens between each word.
- [ ] copy each image to a new folder `/images/posts/<imagename>`, where `<imagename>` is the name of the image file.
- [ ] Add appropriate metadata at the top of the .md file. See example below.

So for this blog post, the folder would be:
`posts/2023/08/03`

And the filename would be `ansible-data-manipulation-with-a-filter`

Images go to  `/images/posts/ansible-data-manipulation-with-a-filter/foo.png` for example.

And the metadata at the top of the file would be:

```
---
title: Ansible data manipulation with a Filter
author: Sean Sullivan
date: 2023-08-03 13:00:00
slug: ansible-data-manipulation-with-a-filter
category: developer
tags: developer
type: text
---
```

**Comment by leogallego** [comment]
@samccann this one is tricky, we don't have the categories for everything yet. I would leave the category as developer but add a couple of tags:

```
category: developer
tags: developer, filters, playbook
```
