### ISSUE TITLE
[Blog] Port How to use the new Constructed Inventory Feature in Ansible Automation Platform 2.4 to .md

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#313]
In an effort to move important community blog posts from Ansible.com to the new website, we want to take https://www.ansible.com/blog/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4 and convert it to .md here in this repository.  
The steps to do this are:

- [ ] Create a set of folders under `/posts` that have:
  * `<year/month/day>`  
- [ ] convert the content to .md with a filename that matches the blog title, all lower-case with hyphens between each word.
- [ ] copy each image to a new folder `/images/posts/<imagename>`, where `<imagename>` is the name of the image file.
- [ ] Add appropriate metadata at the top of the .md file. See example below.

So for this blog post, the folder would be:
`posts/2023/06/29`

And the filename would be `how-to-use-the-new-constructed-inventory-feature-in-aap-2.4`

Images go to  `/images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/foo.png` for example.

And the metadata at the top of the file would be:

```
---
title: How to use the new Constructed Inventory Feature in Ansible Automation Platform 2.4
author: Alan Rominger
date: 2023-06-29 13:00:00
slug: how-to-use-the-new-constructed-inventory-feature-in-aap-2.4
category: awx
tags: awx
type: text
---
```

**Comment by leogallego** [comment]
@samccann category looks good. Adding a couple of tags:

`tags: awx, inventory, smart inventory, constructed inventory`
