### ISSUE TITLE
Hero section: "Learn about Red Hat Ansible Automation Platform" should appear as a link text to indicate it is clickable

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#350]
In the hero section, similar to the "View more" or "Back to top" buttons, the "Learn about Red Hat Ansible Automation Platform ->" should appear as the same color, with only the text itself being clickable. On hover, the text would appear underlined. This would help with accessibility as well as it would indicate to the user that the text is clickable. 

Proposed:
![Screenshot 2024-01-03 at 2 20 58 PM](https://github.com/ansible-community/community-website/assets/98424339/0db2a725-88d0-478e-9df2-c97463c4c0a4)

Current areas with the same interaction:
<img width="1728" alt="Screenshot 2024-01-03 at 2 22 32 PM" src="https://github.com/ansible-community/community-website/assets/98424339/b12944ba-f6dc-4bc2-91ff-27c503b20905">

**Comment by oraNod** [comment]
Nice catch @tiyiprh Thanks!

One note that the text appeared as underlined on hover so there should be no change there. Please let me know if you aren't seeing that though. You can find the PR preview build here: https://ansible-community-website--352.org.readthedocs.build/#
