### ISSUE TITLE
Forum link title

### ISSUE THREAD

**Issue by wbentley15** [ansible-community/community-website#357]
Howdy...wanted to open up the debate as to whether the forum link at the top navigation should read "Ansible community forum" or "Forum" or "Community Forum".  Thoughts?

**Comment by oraNod** [comment]
At some point I remember asking @GregSutcliffe this and we landed on "Ansible community forum" for clarity as well as consistency.

**Comment by cybette** [comment]
Yes we discussed and agreed on Ansible Community Forum (should we have capitalization for the proper noun?)

We want to make sure it is not mistaken as a customer support forum, but still welcoming to everyone in the community (which customers are a part of).

**Comment by oraNod** [comment]
@cybette I think we should stick with sentence case for consistency across the website. Thanks for confirming the link title is correct.
