### ISSUE TITLE
Mission statement: incorporate to the community website

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-website#370]
The Ansible community mission statement below in the description were defined in the following topics:
- https://forum.ansible.com/t/ansible-mission-statement-brainstorming-time/176
- https://forum.ansible.com/t/define-our-community-mission-statement/2101

A mission statement is an attribute of any mature project, so it should be shown on the new website, probably on its homepage.
Please consider incorporating the statements:
```
Our Mission
In the Ansible community, our mission is to produce, maintain, and popularize simple, flexible,
and powerful open-source software tools tailored to automating a large variety of tasks.

We strive to innovate in making infrastructure configuration and management as effortless and
efficient as possible with automation, enabling people to focus on their core objectives.

We welcome members from all skill levels to participate in our open, inclusive, and vibrant community.
Whether you are an expert or just beginning your journey with Ansible, you are encouraged to contribute,
share insights, and collaborate with fellow enthusiasts!
```

**Comment by oraNod** [comment]
Thanks for this @Andersson007 ! @tiyiprh could you please take a look and give some advice on how we should incorporate the mission statement into the homepage?

**Comment by tiyiprh** [comment]
What if we added it to the community section under the links?

<img width="938" alt="Screenshot 2024-01-16 at 12 32 13 PM" src="https://github.com/ansible-community/community-website/assets/98424339/90795363-d432-45eb-8f19-b86180a06eff">
