### ISSUE TITLE
Updates to Ecosystem landing page

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#376]
From the "View more" on the ecosystem section on the landing page and the "Ansible ecosystem" from the Resources dropdown, the user should land on the Ecosystem landing page. To be consistent with the look and feel of the ecosystem cards from the landing page, proposing some updates.

The cards should be the same kind of cards from the landing page with a max height of the project that has the most links. Each project should also have the logo. We may need to create some more logos or placeholders for project that do not have one.

The spacing between the cards and rounded corners for this and the Ansible community training should be the same if possible.

![Ansible Ecosystem](https://github.com/ansible-community/community-website/assets/98424339/f96a957b-65e7-4e0f-9240-734cb4e42140)

**Comment by oraNod** [comment]
@tiyiprh Thanks a mill for this. Yes, I think we'll need more logos for projects. A lot of them don't really have anything.

**Comment by tiyiprh** [comment]
Are the projects currently listed in the Ansible ecosystem page the full list of projects available?

**Comment by oraNod** [comment]
@tiyiprh Yes that should be the full and up to date list of projects, apart from Receptor which is intentionally omitted from the ecosystem page.

**Comment by tiyiprh** [comment]
What if we use the Ansible upstream logo for now for the projects that do not have an icon/logo? And we can slowly try to create one for these ones that are missing?

**Comment by wbentley15** [comment]
@tiyiprh Again another great idea and we use just use the upstream logo until we have a icon/logo for the project.  Going back to my question posed in other issues, who is responsible for implementing these changes?  Is it @oraNod or have you been applying updates also?  Really want to get this into our launch of March 15th.

**Comment by tiyiprh** [comment]
@wbentley15 Unfortunately, implementing these changes is not my area of expertise. @oraNod has been doing the heavy lifting of applying all these updates!

**Comment by oraNod** [comment]
@wbentley15 I can do this one next week if you'd like. I think the suggestion from @tiyiprh is great but wasn't sure if it's something we should push for before launch. Just let me know what you think.

**Comment by wbentley15** [comment]
Yes ***@***.*** if you can get something going next week that would be awesome.Thanks,WalterOn Feb 8, 2024, at 1:53 AM, Don Naro ***@***.***> wrote:﻿
@wbentley15 I can do this one next week if you'd like. I think the suggestion from @tiyiprh is great but wasn't sure if it's something we should push for before launch. Just let me know what you think.
