### ISSUE TITLE
Maintain current urls for migrated blog posts

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#384]
We need a method to maintain the current urls of any migrated blog posts. This issue follows up on #304 and is required as part of #300 

Let's consider an example blog post:

- Dev site: https://ansible-community-website.readthedocs.io/blog/archive/ansible-tips-and-tricks-dealing-with-unreliable-connections-and-services/
- Current production url: https://www.ansible.com/blog/ansible-tips-and-tricks-dealing-with-unreliable-connections-and-services

At launch a url of `ansible.com/blog/archive/ansible-tips-and-tricks-dealing-with-unreliable-connections-and-services/` will result in a 404 for the current production url.

Nikola provides two ways to handle this:

Option 1: Configure [nikola redirection tuples](https://getnikola.com/handbook.html#redirections) in `conf.py`. This works but even nikola docs seem to discourage it. Redirects work best at the web server level, which can add overhead to the operations side of things.

Option 2. Move all the migrated blog posts to a `blog-achive` folder in the repo. Then add this to `conf.py`:

```
POSTS = (
    ("posts/*.md", "blog", "post.tmpl"),
    ("posts/*.rst", "blog", "post.tmpl"),
    ("posts/*.txt", "blog", "post.tmpl"),
    ("posts/*.html", "blog", "post.tmpl"),
    ("blog-archive/*.md", "blog", "post.tmpl"),
)
```

All the migrated posts are then available from `output/blog/` so that the resulting url will match the current production url.

**Comment by samccann** [comment]
Did you mean the production url (currently) to be https://www.ansible.com/blog/ansible-tips-and-tricks-dealing-with-unreliable-connections-and-services ?

**Comment by oraNod** [comment]
> Did you mean the production url (currently) to be https://www.ansible.com/blog/ansible-tips-and-tricks-dealing-with-unreliable-connections-and-services ?

Yep. Thanks for spotting that. I've updated the comment.

**Comment by GregSutcliffe** [comment]
If option 2 is working, then ;ets do it. I'd suggest adding a README to that folder so that we don't accidentally try to move those posts somewhere else in the future
