### ISSUE TITLE
Verify and test migrated blog posts

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#394]
As a final step to ensure #300 is completed successfully and blog posts are migrated as expected, verify and test posts on the dev site. Here are the urls:

https://ansible-community-website.readthedocs.io/blog/archive/active-directory-ansible-tower
https://ansible-community-website.readthedocs.io/blog/archive/a-deeper-look-red-hat-named-a-leader-in-the-forrester-wave
https://ansible-community-website.readthedocs.io/blog/archive/agnostic-network-automation-examples-with-ansible-and-juniper-nre-labs
https://ansible-community-website.readthedocs.io/blog/archive/aix-patch-management-with-ansible
https://ansible-community-website.readthedocs.io/blog/archive/an-introduction-to-windows-security-with-ansible
https://ansible-community-website.readthedocs.io/blog/archive/announcing-the-community-ansible-300-package
https://ansible-community-website.readthedocs.io/blog/archive/ansible-and-infoblox-roles-deep-dive
https://ansible-community-website.readthedocs.io/blog/archive/ansible-and-packer-why-they-are-better-together
https://ansible-community-website.readthedocs.io/blog/archive/ansible-certified-content-collection-for-chocolatey
https://ansible-community-website.readthedocs.io/blog/archive/ansible-community-steering-committee
https://ansible-community-website.readthedocs.io/blog/archive/ansible-data-manipulation-with-a-filter
https://ansible-community-website.readthedocs.io/blog/archive/ansiblefest-2020-is-now-a-virtual-experience
https://ansible-community-website.readthedocs.io/blog/archive/ansiblefest-2021-network-automation-track
https://ansible-community-website.readthedocs.io/blog/archive/ansiblefest-2021-what-means-for-partners
https://ansible-community-website.readthedocs.io/blog/archive/ansible-linting-with-github-actions
https://ansible-community-website.readthedocs.io/blog/archive/ansible-network-resource-purge-parameter
https://ansible-community-website.readthedocs.io/blog/archive/ansible-security-automation-resource-modules
https://ansible-community-website.readthedocs.io/blog/archive/ansible-servicenow-howto-part-3-making-outbound-restful-api-calls-to-ansible-tower
https://ansible-community-website.readthedocs.io/blog/archive/ansible-servicenow-opening-and-closing-tickets
https://ansible-community-website.readthedocs.io/blog/archive/ansible-tips-and-tricks-dealing-with-unreliable-connections-and-services
https://ansible-community-website.readthedocs.io/blog/archive/ansible-tower-advanced-smart-inventory-usage
https://ansible-community-website.readthedocs.io/blog/archive/ansible-tower-jenkins-in-under-5-minutes
https://ansible-community-website.readthedocs.io/blog/archive/ansible-vs.-terraform-demystified
https://ansible-community-website.readthedocs.io/blog/archive/audit-your-vmware-vcenter-server-using-ansible
https://ansible-community-website.readthedocs.io/blog/archive/automating-a-rhel-8-installation-using-the-vmware-rest-ansible-collection
https://ansible-community-website.readthedocs.io/blog/archive/automating-helm-using-ansible
https://ansible-community-website.readthedocs.io/blog/archive/automation-at-the-edge-summit-2022
https://ansible-community-website.readthedocs.io/blog/archive/automation-savings-planner
https://ansible-community-website.readthedocs.io/blog/archive/best-of-fest-2022
https://ansible-community-website.readthedocs.io/blog/archive/best-of-fest-ansiblefest-2020
https://ansible-community-website.readthedocs.io/blog/archive/centralize-your-automation-logs-with-ansible-tower-and-splunk-enterprise
https://ansible-community-website.readthedocs.io/blog/archive/command-module-deep-dive-for-networks
https://ansible-community-website.readthedocs.io/blog/archive/configure-network-cards-by-pci-address-with-ansible-facts
https://ansible-community-website.readthedocs.io/blog/archive/connecting-to-a-windows-host
https://ansible-community-website.readthedocs.io/blog/archive/continuous-detection-and-mitigation-cdm
https://ansible-community-website.readthedocs.io/blog/archive/creating-custom-event-driven-ansible-source-plugins
https://ansible-community-website.readthedocs.io/blog/archive/creating-custom-rules-for-ansible-lint
https://ansible-community-website.readthedocs.io/blog/archive/customer-spotlights-at-ansiblefest-2020
https://ansible-community-website.readthedocs.io/blog/archive/deep-dive-acl-configuration-management-using-ansible-network-automation-resource-modules
https://ansible-community-website.readthedocs.io/blog/archive/deep-dive-into-trend-micro-deep-security-integration-modules
https://ansible-community-website.readthedocs.io/blog/archive/deep-dive-on-ansible-vscode-extension
https://ansible-community-website.readthedocs.io/blog/archive/deep-dive-on-cisco-asa-resource-modules
https://ansible-community-website.readthedocs.io/blog/archive/deep-dive-on-cli-command-for-network-automation
https://ansible-community-website.readthedocs.io/blog/archive/deep-dive-on-vlans-resource-modules-for-network-automation
https://ansible-community-website.readthedocs.io/blog/archive/developing-and-testing-ansible-roles-with-molecule-and-podman-part-1
https://ansible-community-website.readthedocs.io/blog/archive/developing-and-testing-ansible-roles-with-molecule-and-podman-part-2
https://ansible-community-website.readthedocs.io/blog/archive/enable-self-healing-applications-with-ansible-and-dynatrace
https://ansible-community-website.readthedocs.io/blog/archive/event-driven-ansible-is-here
https://ansible-community-website.readthedocs.io/blog/archive/exploring-new-possibilities-with-the-aws-cloud-control-collection
https://ansible-community-website.readthedocs.io/blog/archive/find-and-delete-servicenow-records-en-masse-with-the-updated-ansible-content-collection
https://ansible-community-website.readthedocs.io/blog/archive/five-ways-to-get-started-with-network-automation
https://ansible-community-website.readthedocs.io/blog/archive/genie
https://ansible-community-website.readthedocs.io/blog/archive/getting-started-adding-proxy-support
https://ansible-community-website.readthedocs.io/blog/archive/getting-started-ansible-towers-api
https://ansible-community-website.readthedocs.io/blog/archive/getting-started-ldap-authentication-in-ansible-tower
https://ansible-community-website.readthedocs.io/blog/archive/getting-started-with-ansible-and-check-point
https://ansible-community-website.readthedocs.io/blog/archive/getting-started-with-ansible-collections
https://ansible-community-website.readthedocs.io/blog/archive/getting-started-with-ansible.utils-collection-for-playbook-creators-part-2
https://ansible-community-website.readthedocs.io/blog/archive/getting-started-with-event-driven-ansible
https://ansible-community-website.readthedocs.io/blog/archive/getting-started-with-ospfv2-resource-modules
https://ansible-community-website.readthedocs.io/blog/archive/getting-started-workflow-job-templates
https://ansible-community-website.readthedocs.io/blog/archive/hands-on-with-ansible-collections
https://ansible-community-website.readthedocs.io/blog/archive/how-to-migrate-your-ansible-playbooks-to-support-aws-boto3
https://ansible-community-website.readthedocs.io/blog/archive/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4
https://ansible-community-website.readthedocs.io/blog/archive/how-useful-is-ansible-in-a-cloud-native-kubernetes-environment
https://ansible-community-website.readthedocs.io/blog/archive/infoblox-integration-in-ansible-2.5
https://ansible-community-website.readthedocs.io/blog/archive/installing-and-using-collections-on-ansible-tower
https://ansible-community-website.readthedocs.io/blog/archive/introducing-a-brand-new-way-to-automate-your-azure-cloud
https://ansible-community-website.readthedocs.io/blog/archive/introducing-event-driven-ansible
https://ansible-community-website.readthedocs.io/blog/archive/introducing-the-ansible-api-for-servicenow-itsm
https://ansible-community-website.readthedocs.io/blog/archive/introducing-the-awx-collection
https://ansible-community-website.readthedocs.io/blog/archive/introducing-the-vmware-rest-ansible-content-collection
https://ansible-community-website.readthedocs.io/blog/archive/introduction-to-ansible-builder
https://ansible-community-website.readthedocs.io/blog/archive/introduction-to-ansible-test
https://ansible-community-website.readthedocs.io/blog/archive/kubernetes-meets-event-driven-ansible
https://ansible-community-website.readthedocs.io/blog/archive/kubernetes-operators-ansible-deep-dive-part-1
https://ansible-community-website.readthedocs.io/blog/archive/kubernetes-operators-ansible-deep-dive-part-2
https://ansible-community-website.readthedocs.io/blog/archive/large-scale-deployments-using-ansible
https://ansible-community-website.readthedocs.io/blog/archive/learn-about-edge-automation-at-red-hat-summit-and-ansiblefest-2023
https://ansible-community-website.readthedocs.io/blog/archive/learn-about-event-driven-ansible-at-red-hat-summit-and-ansiblefest-2023
https://ansible-community-website.readthedocs.io/blog/archive/let-ansible-keep-an-eye-on-your-aws-environment
https://ansible-community-website.readthedocs.io/blog/archive/make-your-ansible-playbooks-flexible-maintainable-and-scalable
https://ansible-community-website.readthedocs.io/blog/archive/managing-a-vmware-template-lifecycle-with-ansible
https://ansible-community-website.readthedocs.io/blog/archive/migrating-from-python-virtual-environments-to-automation-execution-environments-in-ansible-automation-platform-2
https://ansible-community-website.readthedocs.io/blog/archive/migrating-to-ansible-collections-webinar-qa
https://ansible-community-website.readthedocs.io/blog/archive/monitoring-as-code-with-sensu-ansible
https://ansible-community-website.readthedocs.io/blog/archive/new-ansible-galaxy
https://ansible-community-website.readthedocs.io/blog/archive/new-libssh-connection-plugin-for-ansible-network
https://ansible-community-website.readthedocs.io/blog/archive/providing-terraform-with-that-ansible-magic
https://ansible-community-website.readthedocs.io/blog/archive/pump-up-your-itil-with-automation
https://ansible-community-website.readthedocs.io/blog/archive/rebooting-network-devices-with-ansible
https://ansible-community-website.readthedocs.io/blog/archive/red-hat-ansible-tower-monitoring-using-prometheus-node-exporter-grafana
https://ansible-community-website.readthedocs.io/blog/archive/red-hat-single-sign-on-integration-with-ansible-tower
https://ansible-community-website.readthedocs.io/blog/archive/released-automation-content-navigator-2.0
https://ansible-community-website.readthedocs.io/blog/archive/securing-tower-installer-passwords
https://ansible-community-website.readthedocs.io/blog/archive/shell-scripts-to-ansible
https://ansible-community-website.readthedocs.io/blog/archive/summary-of-authentication-methods-in-red-hat-ansible-tower
https://ansible-community-website.readthedocs.io/blog/archive/taking-automation-to-the-next-level-using-ansible-gitops-to-manage-the-lifecycle-of-a-containerized-application
https://ansible-community-website.readthedocs.io/blog/archive/terraforming-clouds-with-ansible
https://ansible-community-website.readthedocs.io/blog/archive/the-anatomy-of-automation-execution-environments
https://ansible-community-website.readthedocs.io/blog/archive/the-automation-experience-ansiblefest-2022
https://ansible-community-website.readthedocs.io/blog/archive/the-total-economic-impact-of-red-hat-ansible-tower
https://ansible-community-website.readthedocs.io/blog/archive/the-zen-of-ansible
https://ansible-community-website.readthedocs.io/blog/archive/thoughts-on-restructuring-the-ansible-project
https://ansible-community-website.readthedocs.io/blog/archive/three-quick-ways-to-move-your-ansible-inventory-into-red-hat-ansible-tower
https://ansible-community-website.readthedocs.io/blog/archive/two-simple-ways-automation-can-save-money-on-aws
https://ansible-community-website.readthedocs.io/blog/archive/using-an-inventory-plugin-from-a-collection-in-ansible-tower
https://ansible-community-website.readthedocs.io/blog/archive/using-ansible-automation-platform-gitlab-ce-and-webhooks-to-deploy-iis-website
https://ansible-community-website.readthedocs.io/blog/archive/using-ansible-to-mitigate-network-vulnerabilities
https://ansible-community-website.readthedocs.io/blog/archive/using-infoblox-as-a-dynamic-inventory-in-red-hat-ansible-tower
https://ansible-community-website.readthedocs.io/blog/archive/using-netbox-for-ansible-source-of-truth
https://ansible-community-website.readthedocs.io/blog/archive/using-new-ansible-utilities-for-operational-state-management-and-remediation
https://ansible-community-website.readthedocs.io/blog/archive/using-the-win_dsc-module-in-ansible
https://ansible-community-website.readthedocs.io/blog/archive/using-vmware-vcenter-tags-in-a-red-hat-ansible-tower-dynamic-inventory
https://ansible-community-website.readthedocs.io/blog/archive/walking-on-clouds-with-ansible
https://ansible-community-website.readthedocs.io/blog/archive/welcome-to-the-ansible-lightspeed-technical-preview
https://ansible-community-website.readthedocs.io/blog/archive/whats-new-cloud-automation-with-amazon.aws-6.0.0
https://ansible-community-website.readthedocs.io/blog/archive/windows-package-management
https://ansible-community-website.readthedocs.io/blog/archive/you-are-the-community

**Comment by samccann** [comment]
https://ansible-community-website.readthedocs.io/blog/archive/learn-about-edge-automation-at-red-hat-summit-and-ansiblefest-2023/ has one missing url in the bullet list for Red Hat: Modernizing the industrial manufacturing world

**Comment by samccann** [comment]
I used this page to find the archive - https://ansible-community-website.readthedocs.io/blog/archive.html
And then started at the top with 2023 and used the previous button to review all the 2023 blog posts. Only found the one nit from the prior comment.

**Comment by tiyiprh** [comment]
I started from the top and stopped at this post: https://ansible-community-website.readthedocs.io/blog/archive/automating-a-rhel-8-installation-using-the-vmware-rest-ansible-collection

I just checked to see if they were active sites and in the community patterns. Not sure if there was something else I was supposed to test. I'm not sure if this is too much trouble but could we remove the title that is the line after the author since we already show the title above the author?
This blog post follows the suggested pattern: https://ansible-community-website.readthedocs.io/blog/archive/ansible-data-manipulation-with-a-filter/

Can continue tomorrow!

**Comment by tiyiprh** [comment]
Continued from where I left off yesterday

Leads to a 404: 
https://ansible-community-website.readthedocs.io/blog/archive/getting-started-with-ansible.utils-collection-for-playbook-creators-part-2
https://ansible-community-website.readthedocs.io/blog/archive/infoblox-integration-in-ansible-2.5

Stopped here: https://ansible-community-website.readthedocs.io/blog/archive/make-your-ansible-playbooks-flexible-maintainable-and-scalable/

**Comment by oraNod** [comment]
> I started from the top and stopped at this post: https://ansible-community-website.readthedocs.io/blog/archive/automating-a-rhel-8-installation-using-the-vmware-rest-ansible-collection
> 
> I just checked to see if they were active sites and in the community patterns. Not sure if there was something else I was supposed to test. I'm not sure if this is too much trouble but could we remove the title that is the line after the author since we already show the title above the author? This blog post follows the suggested pattern: https://ansible-community-website.readthedocs.io/blog/archive/ansible-data-manipulation-with-a-filter/
> 
> Can continue tomorrow!

@tiyiprh Thanks for taking a look! Yes, I think we can remove some of the redundant titles. I'll do that in a separate PR after we get the rest of the migrated posts merged.

**Comment by oraNod** [comment]
> Continued from where I left off yesterday
> 
> Leads to a 404: https://ansible-community-website.readthedocs.io/blog/archive/getting-started-with-ansible.utils-collection-for-playbook-creators-part-2 https://ansible-community-website.readthedocs.io/blog/archive/infoblox-integration-in-ansible-2.5
> 
> Stopped here: https://ansible-community-website.readthedocs.io/blog/archive/make-your-ansible-playbooks-flexible-maintainable-and-scalable/

@tiyiprh Thanks so much for checking this. Yes I noticed the 404 too and fixed it in this PR: https://github.com/ansible-community/community-website/pull/403

Some of the urls in the blog posts have characters that get stripped out. Thankfully there's an easy enough fix. Please let me know if you find any more 404s.

And thanks again for checking, this is very helpful! Whatever other oddities or broken bits you can find...

**Comment by tiyiprh** [comment]
I went through the rest and found a couple more 404s:
https://ansible-community-website.readthedocs.io/blog/archive/released-automation-content-navigator-2.0
https://ansible-community-website.readthedocs.io/blog/archive/whats-new-cloud-automation-with-amazon.aws-6.0.0

**Comment by oraNod** [comment]
Thanks a mill @tiyiprh These should be fixed now

I noticed this one was also a 404 https://ansible-community-website.readthedocs.io/blog/archive/infoblox-integration-in-ansible-2.5

**Comment by oraNod** [comment]
Thanks again for all the help with this @tiyiprh It was genuinely helpful. I've just sent another PR that changes all the urls for the migrated blog posts to avoid 404s and broken links with the posts that are currently on "ansible.com". When that PR merges, however, it will result in 404s for all the urls I've listed here.

Since I've already gone through everything myself and just double checked things are OK, I think we can confidently say we've done adequate testing and there are no major issues with the migrated posts.

I'll go ahead and close this one. If anyone wants to do any further testing of the blog posts, please do so from the dev site at: https://ansible-community-website.readthedocs.io/

Feel free to navigate through the posts and report any issues you find. Cheers!

**Comment by oraNod** [comment]
> https://ansible-community-website.readthedocs.io/blog/archive/learn-about-edge-automation-at-red-hat-summit-and-ansiblefest-2023/ has one missing url in the bullet list for Red Hat: Modernizing the industrial manufacturing world

@samccann Thanks for pointing this one out. Really shows that folks have looked at the migrated posts in detail.

As far as this nit is concerned, it exists in the source post. See here: https://www.ansible.com/blog/learn-about-edge-automation-at-red-hat-summit-and-ansiblefest-2023

The <li> looks like a link but there is no href in the source. It's likely a simple error on the part of the original author and not something we should be too concerned about.
