### ISSUE TITLE
Update page content | How Ansible works

### ISSUE THREAD

**Issue by grountre** [ansible-community/community-website#399]
The Ansible web team recently updated the 'How Ansible works' pages on the current ansible.com.

Please go through and update the web content of the page on the community site to reflect these changes.

Currently page with new content: https://www.ansible.com/overview/how-ansible-works
Community site: https://ansible-community-website.readthedocs.io/how-ansible-works/

Let me know if there are questions or concerns.

**Comment by oraNod** [comment]
I believe @wbentley15 resolved this as part of https://github.com/ansible-community/community-website/commit/8c2cd08c68c67d4af5f4c6f718dcc43be9f4a816

I'm going to close this but please feel free to reopen or let us know if further changes are required.
