### ISSUE TITLE
Reconsider selection of projects in the ecosystem section on the homepage

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-website#411]
On the https://ansible-community-website.readthedocs.io/#ecosystem you see

![Screenshot from 2024-01-26 12-37-03](https://github.com/ansible-community/community-website/assets/34477873/42bd077c-e1ef-4780-827b-0dfeaff2ba75)

I think we should have other project in there (e.g runner is not supposed to be used much by end users; there are much widely used projects besides EDA). Instead, how about:
- Ansible Core
- Ansible Navigator: it's a great tool (used btw in Red Hat Certified Engineer course) aiming to provide a common interface to all the ansible utilities + EE support, and more.
- AWX: justification: upstream for Ansible controller, widely used
- Lint / Molecule / VS Code extension / Builder?

**Comment by samccann** [comment]
Is it worth going by github stars or something to find out what's popular?

**Comment by Andersson007** [comment]
> Is it worth going by github stars or something to find out what's popular?

@samccann we could try it as a criteria, sure, though the number of starts can be also affected by a project age.
I think AWX and core will be there anyway. I would suggest giving a chance to Navigator as it's a great tool but young compared to, say, lint or molecule.

**Comment by tiyiprh** [comment]
We currently do not but we can work on creating some. Here is the list of logos we currently have available to use: https://github.com/ansible/logos

Based on the above comment, are these the ones that are going to be on the home page:
Ansible Core
Ansible Navigator
AWX - already there
Lint / Molecule / VS Code extension / Builder (already there)

**Comment by tiyiprh** [comment]
In the meantime, we can just use the upstream Ansible A logo.

**Comment by wbentley15** [comment]
@oraNod Is it safe to say this will be updated prior to our target launch date of March 15th?

**Comment by leogallego** [comment]
I would suggest we keep EDA there, we want to get contributions to the sources/plugins, it's a new upcoming project and needs some extra exposure.

We could group navigator, lint, vscode and builder into a general "dev-tools" one, matching the [new bundle packaging](https://github.com/ansible/ansible-dev-tools) (although we might be missing an umbrella logo for that right now, and might need some extra thinking).

1. Ansible Core
2. Dev-Tools (bundles navigator, lint, etc.)
3. AWX - already there
4. EDA - already there

**Comment by oraNod** [comment]
@wbentley15 Yes, I'm planning to get on this one next week. I'll try and get a PR up Monday.

**Comment by oraNod** [comment]
Of course if someone beats me to it, that's fine too.

**Comment by wbentley15** [comment]
Thank you as ***@***.***,WalterOn Feb 8, 2024, at 2:02 AM, Don Naro ***@***.***> wrote:﻿
@wbentley15 Yes, I'm planning to get on this one next week. I'll try and get a PR up Monday.

**Comment by oraNod** [comment]
I'll tackle this one after we merge #420 - It has some changes to the logos in the image folder that we should incorporate first.
