### ISSUE TITLE
Create Ansible community feature icons

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#48]
The Ansible community site requires some icons. The purpose of this issue is to create SVG icons that represent the following:

– Automate
– Agentless
– Extensible
– Collections
– Open-source
– Ecosystem

We would also like a community AWX logo if there isn't one already.

The new icons should go into this directory: https://github.com/ansible-community/community-website/tree/main/images

**Comment by tiyiprh** [comment]
Would love to help with this!

**Comment by oraNod** [comment]
@tiyiprh Excellent. Please feel free to assign yourself or if you want to coordinate with some other folks. Whatever suits you and is comfortable. Can't wait to see the logos you design!

**Comment by aratti96** [comment]
Tina and I are working together on this one. This is our first iteration of icons:

Automate
<img width="376" alt="Screenshot 2023-04-26 at 10 41 54 AM" src="https://user-images.githubusercontent.com/105744045/234644953-ce0ea2c5-0a3b-4270-bfbf-98d47fc7495e.png">

Agentless
<img width="365" alt="Screenshot 2023-04-26 at 10 42 14 AM" src="https://user-images.githubusercontent.com/105744045/234645019-2e760869-0333-45eb-842f-8c20e6c55226.png">

Extensive
<img width="417" alt="Screenshot 2023-04-26 at 10 42 51 AM" src="https://user-images.githubusercontent.com/105744045/234645174-3535164e-7904-4b4e-96b0-a428e2b2e9a7.png">

Collections
<img width="274" alt="Screenshot 2023-04-26 at 10 43 08 AM" src="https://user-images.githubusercontent.com/105744045/234645251-b386eee2-ab80-4128-8915-37f412959582.png">

Open-Source
<img width="203" alt="Screenshot 2023-04-26 at 10 43 31 AM" src="https://user-images.githubusercontent.com/105744045/234645339-6c69e293-9f38-453e-ae02-f3fa80e71b50.png">

Ecosystem
<img width="310" alt="Screenshot 2023-04-26 at 10 44 02 AM" src="https://user-images.githubusercontent.com/105744045/234645467-9f6b65ea-30a8-4021-b053-c22067e0118b.png">

**Comment by oraNod** [comment]
Thank you @aratti96 and @tiyiprh I'd like to give some more detailed feedback soon but here are some initial thoughts:

- the XML icon for extensible doesn't really fit. maybe if there was a schema but, in this case, it refers to programmatic extensibility via API

- agentless might well be combined with secure "agentless and secure" - and that suggested icon is on the right track but maybe it would be better if the controller wasn't a different icon to the managed nodes. maybe something like this (without the cloud): https://github.com/infinispan/infinispan.github.io/blob/develop/assets/images/documentation/icon-cloud.png

I'm not sure but I think I see some of these in the noun project. Have you seen the icons we already have? They might help give some additional inspiration: https://github.com/ansible-community/community-website/tree/main/themes/ansible-community/assets/images

**Comment by aratti96** [comment]
@oraNod Thank you! Yes I found these on the noun project for a first stab. I was struggling with the extensible one, and will try to find one that is maybe more like the one in the second link you sent.

**Comment by aratti96** [comment]
Here are updated suggestions on agentless and extensible:

Agentless:
<img width="363" alt="Screenshot 2023-04-27 at 12 19 41 PM" src="https://user-images.githubusercontent.com/105744045/234956177-d5c8d292-3784-4edf-84a8-7f96f0a7e53d.png">

Extensible:
<img width="399" alt="Screenshot 2023-04-27 at 12 20 05 PM" src="https://user-images.githubusercontent.com/105744045/234956284-4f39201d-6945-4db1-be52-f2bc17321b8e.png">
