### ISSUE TITLE
Banner icon for the homepage

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#49]
Ansible community banner icon for the homepage. Something to replace the "ansible.com" community banner: https://www.ansible.com/hubfs/2015_Images/Community/ansible-community-header-bg.jpg

![image](https://user-images.githubusercontent.com/32749632/233343373-db59a4b6-64f3-41cd-9187-e44e42da3392.png)

**Comment by tiyiprh** [comment]
Issue #57 has our proposed banner for now. We will continue to look at potentially incorporating the Ansibull to the banner.

**Comment by tiyiprh** [comment]
Updated banner:
![Screenshot 2023-08-29 at 7 29 41 AM](https://github.com/ansible-community/community-website/assets/98424339/c8cc3c56-dd6b-4046-825e-f4bc58aa0567)
![conny-schneider-xuTJZ7uD7PI-unsplash](https://github.com/ansible-community/community-website/assets/98424339/971d5baa-c3d6-4688-9e0c-1b48de44514f)
I flipped the above image horizontally and brought the opacity down to 60%. 
I added a rectangle above that in the color: Hex code: 5BBDBF and brought the opacity down to 80%
