### ISSUE TITLE
Ansible community mascot

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#50]
Ansibull is great and the OG mascot based on https://twitter.com/ansibull

You can see Ansibull in places like the Bullhorn:

![image](https://user-images.githubusercontent.com/32749632/233344395-b17a6d7c-817a-4bee-93f9-3610136d39dc.png)

One piece of feedback from the Ansible community team has gathered is that Ansibull is maybe not the most all-round best representation of the actual humans in the Ansible community. Part of the issue might be that bulls need to be depicted as quite masculine otherwise they can be mistaken for cows.

The purpose of this issue is to consider a mascot revamp that all contributors can identify with and see as a welcoming companion. There to help you do awesome automation. Also this issue should not try to replace Ansibull. Maybe just sort of a facelift.

**Comment by oraNod** [comment]
We can maybe also borrow some inspiration from the colouring book: https://github.com/FOSS-Coloring-Books/ansible

**Comment by cybette** [comment]
Some of the "baby bull" logos [here](https://github.com/ansible/logos) are cute as well

**Comment by oraNod** [comment]
Thanks, @cybette I just edited the description. I realized maybe it wasn't clear enough that we shouldn't replace Ansibull.

**Comment by tiyiprh** [comment]
Would love to work on this one as well!

**Comment by aratti96** [comment]
![Ansibull-community](https://github.com/ansible-community/community-website/assets/105744045/25ba4653-1bfa-4783-94a4-bc783b1fc104)

Here is our first try of an updated Ansibull based on community feedback.

**Comment by oraNod** [comment]
Thanks for the amazing work @tiyiprh and @aratti96 I think we can close this and use https://github.com/ansible/logos/tree/main/ansibull-community
