### ISSUE TITLE
Fix the footer

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#51]
Footer doesn't span full width and looks centered from the left margin.

**Comment by tiyiprh** [comment]
Can take this one as well

**Comment by tiyiprh** [comment]
Sorry all! Taking another look at this, this is probably not my area of expertise as I do not know CSS.

**Comment by GregSutcliffe** [comment]
@tiyiprh no need to apologise! Thanks for taking a look anyway :)
