### ISSUE TITLE
Fix the CSS in the Navigation submenus

### ISSUE THREAD

**Issue by GregSutcliffe** [ansible-community/community-website#53]
There is a button attribute (maybe `class="btn btn-primary"`) in the submenus that causes a red background on click.

![image](https://user-images.githubusercontent.com/32749632/233474981-b1ed231d-e1d8-43c3-a11f-78c80f838418.png)

**Comment by GregSutcliffe** [comment]
@vidyanambiar any idea what's causing this?

**Comment by vidyanambiar** [comment]
@GregSutcliffe That color is being set [here](https://github.com/ansible-community/community-website/blob/main/themes/ansible-community/sass/_nav-bar.scss#L20). This is how it was originally with the ansible.com stylesheet. When I removed that stylesheet, this background color for the active menu item defaulted to blue (via bootstrap), so I put the customization in the code linked above to maintain the original styling. Having the active menu item highlighted appears to be standard styling from ansible.com/bootstrap but we can change it in the custom css if needed.

**Comment by oraNod** [comment]
Fixed with #207
