### ISSUE TITLE
Wireframe: Community section

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#80]
Implement the "Community" section from the wireframe issue #57 

This should result in a file such as `template/homepage-something-band.tmpl` along with the associated `themes/ansible-community/sass/_homepage-something-band.scss` definition.

**Comment by cybette** [comment]
As @leogallego mentioned [here](https://github.com/ansible-community/community-website/issues/57#issuecomment-1581172483), this is the _"community feature bar" where we describe some of the platforms options to engage the community (matrix, forum, github, mastodon, twitter, etc.)_

I think it should definitely have Matrix and Forum, followed by GitHub. Mastodon is nice to have but can be more of a social icon in the header/footer. I would exclude Twitter/X.

**Comment by leogallego** [comment]
I was thinking a bit on the options here and thought of different categories, but in the end, they are all about community/socializing. Drilling down on the options and sorting:

Official channels
1. Forums (will be live by this time and should be the first option for most users)
1. Matrix (and maybe IRC?)
1. Maling lists (current)
1. Mastodon `@ansible@fosstodon.org` (we have a thriving community there, I agree on the header/footer + having the icon in more places won't hurt)
1. Youtube `https://www.youtube.com/ansiblecommunity`
1. Linkedin `https://www.linkedin.com/groups/4648083/`
1. Meetup list all" page?
1. Facebook? Does someone still use it?

Devs & Contributors (maybe this can be a second row?)
1. Github (github.com/ansible)
1. Github (github.com/ansible-community)
1. Github (github.com/ansible-collections)

*Github note*: They all allow community participation and have different focus. Below the icons we may need a small description to communicate the difference.

Twitter/X agree, we don't have a Community account, so linking here might not be a good option

**Comment by oraNod** [comment]
>     8. Facebook? Does someone still use it?

Ha. I think I know someone on our team who might... :laughing:

**Comment by cybette** [comment]
Lol, I vote NO for facebook. It's not about people using it (yeah I still do to stay in touch with friends and family), it's about using it for a project community. There has never been an official Ansible Community FB page (that I'm aware of), and even the product FB page has been rolled up into the RH company page. So let's drop FB for sure.
