### ISSUE TITLE
Wireframe: Events

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-website#83]
Implement the "Contribute" section from the wireframe issue #57 

This should result in a file such as `template/homepage-something-band.tmpl` along with the associated `themes/ansible-community/sass/_homepage-something-band.scss` definition.

See @GregSutcliffe for Discourse integration.

**Comment by cybette** [comment]
My schedule's packed this week but if noone gets to this by the end of the week, I'll take this.

**Comment by oraNod** [comment]
@cybette Hey, sorry I just noticed this comment. I was thinking about starting this one today and assigned myself. Would you prefer to take it? I can work on something else.

**Comment by cybette** [comment]
@oraNod please go ahead, thanks! Should I add event images here in the comments, or is this only for the wireframe and not the content?

**Comment by oraNod** [comment]
@cybette Yes, please add the images here. I made a comment in the matrix chat that maybe we could drop the events page on the site altogether. Perhaps we could add your images directly on the homepage as the wireframe is pretty much empty for the events section.

**Comment by cybette** [comment]
Here's the one for community day; contributor summit coming up!
![Community_day_202309-berlin](https://github.com/ansible-community/community-website/assets/2913667/db1aec05-862c-474a-9e94-2ed7c6fb9681)
